### ISSUE TITLE
EMA questions when resume

### ISSUE THREAD

**Issue by Laughing-q** [ultralytics/yolov5#310] opened 2020-07-06 13:42 UTC
I see that the EMA is saved during checkpointing instead of the normal model, but when I resume, the  old EMA become a new normal model, then restart computing EMA(self.updates=0).   what i expect is that normal model resume from normal model and EMA resume from old EMA. is that right ? Should we save both normal model and EMA?

**Comment by NanoCode012** [comment] 2020-07-06 16:53
ema creates a deep copy of model at `ema.ema`. We are saving that. The issue is with resume. I believe there's a few Issues on it. I suggest to train only one time and not need to resume as of right now.

**Comment by glenn-jocher** [comment] 2020-07-06 17:40
@Laughing-q yes that is correct, to better resume correctly we'd want to save both the model and the ema, as well as the optimizer, and then replace all correctly on resume.

**Comment by glenn-jocher** [comment] 2020-07-09 04:43
@Laughing-q thanks for raising the issue! I'll close it as duplicate of #292 so we can focus the conversation there.

**Closed as completed by glenn-jocher** 2020-07-09 04:43 UTC
