### ISSUE TITLE
Model predict with forward will fail if PIL image does not have filename attribute

### ISSUE THREAD

**Issue by robmarkcole** [ultralytics/yolov5#2702] opened 2021-04-05 04:51 UTC
## 🐛 Bug
forward [here](https://github.com/ultralytics/yolov5/blob/d2e754b67bc08d3634df05932cc94d8c9314a7b1/models/common.py#L203) checks for the filename attribute on a PIL image and will fail with `ValueError: PosixPath('.') has an empty name` if not present. This is the case if the PIL image is created from bytes. My hacky solution is below:

```
# read file
img_bytes = file.read() 
img = Image.open(io.BytesIO(img_bytes))
img.save('/tmp/tmp.jpg')

# Reopen
img = Image.open('/tmp/tmp.jpg')
results = model(img, size=640)
```

## To Reproduce (REQUIRED)
Run `model(Image.open(io.BytesIO(img_bytes)), size=640)`

## Expected behavior
No failure if no filename attribute

## Additional context
Previously referenced in https://github.com/ultralytics/yolov5/issues/2246

**Comment by glenn-jocher** [comment] 2021-04-05 10:39
@robmarkcole thanks for the bug report! I can reproduce with the following. It looks like we'll need a more robust filename attribute:

```python
    import torch
    from PIL import Image

    model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
    img = Image.new('RGB', (640, 640))
    results = model(img)
```

**Comment by glenn-jocher** [comment] 2021-04-05 20:22
@robmarkcole I've pushed a fix for this in PR #2708. Does this resolve your original issue? My reproduction code now runs correctly. Nameless images are assigned a default name now, i.e. image3.jpg for batch index 3, which is later replaced if a more suitable replacement is found.

## Input
```python
import torch
from PIL import Image

model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)  # recache latest code
img = Image.new('RGB', (640, 640))
results = model(img)
results.print()
results.save()
```

## Output
```
Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to /root/.cache/torch/hub/master.zip

                 from  n    params  module                                  arguments                     
  0                -1  1      3520  models.common.Focus                     [3, 32, 3]                    
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     18816  models.common.C3                        [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  1    156928  models.common.C3                        [128, 128, 3]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  1    625152  models.common.C3                        [256, 256, 3]                 
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8                -1  1    656896  models.common.SPP                       [512, 512, [5, 9, 13]]        
  9                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]          
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]          
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]          
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 24      [17, 20, 23]  1    229245  models.yolo.Detect                      [80, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model Summary: 283 layers, 7276605 parameters, 7276605 gradients

YOLOv5 🚀 2021-4-5 torch 1.8.1+cu101 CUDA:0 (Tesla P100-PCIE-16GB, 16280.875MB)

Adding autoShape... 
image 1/1: 640x640
Speed: 5.0ms pre-process, 14.3ms inference, 0.6ms NMS per image at shape (1, 3, 640, 640)
Saved image0.jpg to runs/hub/exp2
```

**Comment by robmarkcole** [comment] 2021-04-06 03:55
@glenn-jocher I am afraid the issue persists, to reproduce:

```python
import io
import torch
from PIL import Image

# Model
model = torch.hub.load("ultralytics/yolov5", "yolov5s", pretrained=True, force_reload=True)

# img = Image.open("zidane.jpg")  # PIL image, succeeds

# Reading bytes fails
with open("zidane.jpg", "rb") as file:
    img_bytes = file.read()
img = Image.open(io.BytesIO(img_bytes))

print(img.size) # validate image
results = model(img, size=640)  # includes NMS
results.print()
```

**Comment by glenn-jocher** [comment] 2021-04-06 11:08
@robmarkcole thanks for the additional code! I can reproduce now with a slightly modified version in Colab:

```bash
import io
import torch
from PIL import Image

# Model
model = torch.hub.load("ultralytics/yolov5", "yolov5s", pretrained=True, force_reload=True)

# Images
for f in ['zidane.jpg', 'bus.jpg']:  # download 2 images
    print(f'Downloading {f}...')
    torch.hub.download_url_to_file('https://github.com/ultralytics/yolov5/releases/download/v1.0/' + f, f)

# Reading bytes fails
with open("zidane.jpg", "rb") as file:
    img_bytes = file.read()
img = Image.open(io.BytesIO(img_bytes))
# img = Image.open("zidane.jpg")  # PIL image, succeeds

print(img.size) # validate image
results = model(img, size=640)  # includes NMS
results.print()
```

**Closed as completed** 2021-04-06 11:18 UTC
Labels: bug

**Comment by glenn-jocher** [comment] 2021-04-06 11:22
@robmarkcole original issue should be resolved now in #2718. Please try again and let us know if you run into any other problems!

**Comment by glenn-jocher** [comment] 2021-04-06 11:22
<img width="1236" alt="Screenshot 2021-04-06 at 13 21 21" src="https://user-images.githubusercontent.com/26833433/113703420-19d00700-96db-11eb-88b1-fe5fba807a67.png">

**Comment by robmarkcole** [comment] 2021-04-06 13:30
Can confirm this is resolved
