### ISSUE TITLE
YOLOv5 for video tracking and detection

### ISSUE THREAD

**Issue by eylonmiz22** [ultralytics/yolov5#4165] opened 2021-07-26 15:35 UTC
Hey there!
Thank you for your awesome project, which I admire.

I wonder if I could use the YOLOv5-transformer version to detect objects in a frame sequence, extracted from an input video.
I guess that a mixture between your great work and the transformer architecture may lead to better results when talking about videos, as frame positioning is crucial for the detection of other frames' objects.

If it is already implemented, what should the shapes of the inputs be? Should the batch dimension be compatible with the order of the frames?

Again, thank you very much,
Eylon

**Comment by glenn-jocher** [comment] 2021-07-26 16:47
@eylonmiz22 duplicate of https://github.com/ultralytics/yolov5/issues/2329

**Comment by eylonmiz22** [comment] 2021-07-27 07:40
Thanks for the quick replay @glenn-jocher 

I already noticed this issue about the transformer integration with the backbone.
My goal is to track and detect objects' locations in a video by finding the relevant relations between the locations of objects within frames in different timestamps.

Just wanted to ensure that the dimension of the batch_size could really support different timestamps of video frames because I expected the input shape to be (batch_size, time_dimension/sequence_size, channels, height, width), but the transformer block expects only (batch_size, channels, height, width).

Does the batch_size need to be sorted by the order of the timestamps (frames) in order to make the detection decision of a frame to consider the objects' location from the former/next frames?

Again, thank you!

**Comment by glenn-jocher** [comment] 2021-07-27 13:46
@eylonmiz22 https://github.com/ultralytics/yolov5/issues/2329 provides transformer modules for YOLOv5.

Customization beyond that is up to you.

**Closed as completed** 2021-07-28 12:13 UTC
Labels: question
