### ISSUE TITLE
Failure to train

### ISSUE THREAD

**Issue by edeyejedi** [ultralytics/yolov5#596] opened 2020-08-01 12:01 UTC
Rerunning a training run that worked previously and get the following after train.py checks out all the inputs........

Image sizes 416 train, 416 test
Using 2 dataloader workers
Starting training for 250 epochs...
    Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
  0% 0/21 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 461, in <module>
    train(hyp, tb_writer, opt, device)
  File "train.py", line 284, in train
    loss, loss_items = compute_loss(pred, targets.to(device), model)  # scaled by batch_size
  File "/content/yolov5/utils/utils.py", line 496, in compute_loss
    lcls *= h['cls'] * s
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.
  0% 0/21 [00:02<?, ?it/s]

However also getting: 

Setup complete. Using torch 1.6.0+cu101 _CudaDeviceProperties(name='Tesla T4', major=7, minor=5, total_memory=15079MB, multi_processor_count=40)
/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py:125: UserWarning: 
Tesla T4 with CUDA capability sm_75 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the Tesla T4 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))

So could be related the hardware Colab is supplying me with? 
Not sure how much I can help as it is well above my pay grade :)

**Comment by fho306** [comment] 2020-08-01 13:12
Duplicate of #594

**Comment by glenn-jocher** [comment] 2020-08-01 18:50
Resolved in #593. Closing as duplicate.

**Closed as completed by glenn-jocher** 2020-08-01 18:50 UTC
Labels: bug
