### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'

### ISSUE THREAD

**Issue by Powercube7** [ultralytics/yolov5#7482] opened 2022-04-19 14:10 UTC
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

When trying to train a model, I get a HUGE error that ends with the name of the issue. This never happened before and started when I upgraded PyTorch to the latest version.

![image](https://user-images.githubusercontent.com/80365192/164023077-419e7187-ab49-4dbc-84b7-3ca2529e0501.png)
here is a screenshot of the error. One thing I have found is that using 0 data loader workers avoids this issue, but such a thing neglects the whole point of having a GPU. I heard this might be a PyTorch issue so I hope it gets fixed ASAP

### Environment

- Latest YOLO version to date, PyTorch 1.11.0 + cuda 11.3
- OS: Windows 10
- Python Version: 3.8.0

### Minimal Reproducible Example

!python train.py --img 480 --batch 20 --epochs 50 --data model.yaml --weights yolov5s.pt --workers 2

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment] 2022-04-19 22:52
@Powercube7 closing as duplicate of #6962

**Closed as completed by glenn-jocher** 2022-04-19 22:52 UTC
Labels: bug, duplicate

**Comment by szrong** [comment] 2022-06-22 04:35
......
Exception ignored in: <function StorageWeakRef.__del__ at 0x0000021CD5EAD160>
Traceback (most recent call last):
  File "C:\Users\rongsiji\.conda\envs\yolov5\lib\site-packages\torch\multiprocessing\reductions.py", line 36, in __del__
  File "C:\Users\rongsiji\.conda\envs\yolov5\lib\site-packages\torch\storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
......

**Comment by glenn-jocher** [comment] 2022-06-22 09:56
@szrong known pytorch issue, duplicate of https://github.com/ultralytics/yolov5/issues/6962
