### ISSUE TITLE
cutout

### ISSUE THREAD

**Issue by zwhua006** [ultralytics/yolov5#5813] opened 2021-11-28 11:12 UTC
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I use cutout,like this:

        # Albumentations
        img, labels = self.albumentations(img, labels)
        nl = len(labels)  # update after albumentations

        # HSV color-space
        augment_hsv(img, hgain=hyp['hsv_h'], sgain=hyp['hsv_s'], vgain=hyp['hsv_v'])

        # Flip up-down
        if random.random() < hyp['flipud']:
            img = np.flipud(img)
            if nl:
                labels[:, 2] = 1 - labels[:, 2]

        # Flip left-right
        if random.random() < hyp['fliplr']:
            img = np.fliplr(img)
            if nl:
                labels[:, 1] = 1 - labels[:, 1]

        # Cutouts
        labels = cutout(img, labels, p=0.5)

    labels_out = torch.zeros((nl, 6))
    if nl:
        labels_out[:, 1:] = torch.from_numpy(labels)

    # Convert
    img = img.transpose((2, 0, 1))[::-1]  # HWC to CHW, BGR to RGB
    img = np.ascontiguousarray(img)

but the error appears:
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/project/train/src_repo/yolov5/utils/datasets.py", line 616, in __getitem__
    labels_out[:, 1:] = torch.from_numpy(labels)
RuntimeError: The expanded size of the tensor (12) must match the existing size (10) at non-singleton dimension 0.  Target sizes: [12, 5].  Tensor sizes: [10, 5]
and why?
when I not use cutout,it's ok.

**Comment by glenn-jocher** [comment] 2021-11-28 13:39
@zwhua006 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. Your issue is not reproducible. 

I imported utils.augmentations.cutout and uncommented cutout here and trained a few epochs of COCO128. Everything works correctly:
https://github.com/ultralytics/yolov5/blob/fcd180d33697848ea7acb96d7485c58110704d5e/utils/datasets.py#L612-L614

![train_batch0](https://user-images.githubusercontent.com/26833433/143770260-db799e64-b983-4907-a1fb-6ef2f476922b.jpg)

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by NikaMasa51** [comment] 2021-12-03 07:23
I encountered a similar event. Moreover, it was observed even when using the default coco128.yaml configuration file.
The problem seems to be happening at the timing of calling the bbox_ioa function in the cutout function of augmentations.py.
It seems that sometimes the variable shape changes when I enter the labels variable into this function. For example, (3, 5) → (1, 5) or (3, 5) → (2, 5)
The strange thing is that it happens from time to time.
Sometimes successful when the bbox_ioa function is called.
But sometimes the variable shape of ioa is not equal to the shape of labels.
Currently, it seems that the specification is to check the value in ioa and remove boxes larger than 60 from the labels variable.
In that case, the length of labels is also changed, but it seems that the nl variable (length of labels) is not changed accordingly.
What do you think of this?

![image](https://user-images.githubusercontent.com/48128380/144576257-92b9e383-6064-4a5e-8841-c3d797e6dbbc.png)

↑
I think that it is the solution to add the code 'nl = len(labels) ' behind calling cutout function.

All I did was import utils.augmentations.cutout, comment out the description about the cutout function, and train some epochs of the default COCO128, as you explained.
Could you please solve this problem?
I just want to use the cutout process comfortably.

**Comment by glenn-jocher** [comment] 2021-12-03 14:29
@zwhua006 @NikaMasa51 good news 😃! Your original issue may now be fixed ✅ in PR #5873. This PR updates number of labels variable `nl` after `cutout()` function.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Closed as completed** 2021-12-03 14:28 UTC
Labels: question
