### ISSUE TITLE
why i can't use webcam for real-time detect

### ISSUE THREAD

**Issue by cartoonkeng** [ultralytics/yolov5#2868] opened 2021-04-20 17:58 UTC
## ❔Question
I try to use  'python3 detect.py --source 0' for webcam detect but it's not work 
it give me output like this 
```
 1/1: 0... Traceback (most recent call last):
  File "detect.py", line 178, in <module>
    detect()
  File "detect.py", line 51, in detect
    dataset = LoadStreams(source, img_size=imgsz, stride=stride)
  File "/home/caton/yolov5/utils/datasets.py", line 279, in __init__
    if 'youtube.com/' in url or 'youtu.be/' in url:  # if source is YouTube video
TypeError: argument of type 'int' is `not iterable
```

Anyone know how to fix it?

**Comment by josenxx** [comment] 2021-04-20 19:56
I have the same issue on ubuntu 20.04 LTS and the errror message is the same.


Update 1: webcam works fine on MAC
Update 2: 
Pytorch 1.8.1 + ubuntu  = webcam does not work
Pytorch 1.9 + ubuntu  = webcam does not work
Pytorch 1.8.1 + mac  = webcam works
Pytorch 1.9 + mac  = webcam works

It seems to be a ubuntu issue

**Comment by glenn-jocher** [comment] 2021-04-20 21:19
@josenxx @cartoonkeng this is a bug due to YouTube integration which was fixed in https://github.com/ultralytics/yolov5/pull/2818. Please `git pull` or `git clone` to receive this update and let us know if you have any other issues or feedback. Thank you!

**Comment by glenn-jocher** [comment] 2021-04-20 21:21
@josenxx @cartoonkeng closing as duplicate of issue https://github.com/ultralytics/yolov5/issues/2810. 

Please review existing issues prior to opening new ones, thank you!

**Closed as completed by glenn-jocher** 2021-04-20 21:21 UTC
Labels: duplicate, question

**Comment by cartoonkeng** [comment] 2021-04-21 06:44
Thank you all a lot I'll try
