### ISSUE TITLE
using .engine file as weight argument occur error

### ISSUE THREAD

**Issue by Need-an-AwP** [ultralytics/yolov5#10089] opened 2022-11-09 05:20 UTC
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

i used the export.py to export a tensorrt model, but it can't be used successfully by detect.py
other model files like .pt and .onnx are working normally 

```
(strongsort) D:\AIII\Yolov5_StrongSORT_OSNet-master>python ./yolov5/detect.py --weights ./weights/best.engine --source "Desktop 2022.11.08 - 20.02.31.01.mp4" --imgsz 1056 --view-img
detect: weights=['./weights/best.engine'], source=Desktop 2022.11.08 - 20.02.31.01.mp4, data=yolov5\data\coco128.yaml, imgsz=[1056, 1056], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=True, save_txt=False, save_c
onf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=yolov5\runs\detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, ha
lf=False, dnn=False, vid_stride=1
YOLOv5  2022-11-8 Python-3.10.6 torch-1.13.0 CUDA:0 (NVIDIA GeForce RTX 3070 Laptop GPU, 8192MiB)

Loading weights\best.engine for TensorRT inference...
Traceback (most recent call last):
  File "D:\AIII\Yolov5_StrongSORT_OSNet-master\yolov5\detect.py", line 258, in <module>
    main(opt)
  File "D:\AIII\Yolov5_StrongSORT_OSNet-master\yolov5\detect.py", line 253, in main
    run(**vars(opt))
  File "C:\Users\17904\anaconda3\envs\strongsort\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\AIII\Yolov5_StrongSORT_OSNet-master\yolov5\detect.py", line 95, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
  File "D:\AIII\Yolov5_StrongSORT_OSNet-master\yolov5\models\common.py", line 391, in __init__
    import tensorrt as trt  # https://developer.nvidia.com/nvidia-tensorrt-download
  File "C:\Users\17904\anaconda3\envs\strongsort\lib\site-packages\tensorrt\__init__.py", line 129, in <module>
    ctypes.CDLL(find_lib(lib))
  File "C:\Users\17904\anaconda3\envs\strongsort\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] 找不到指定的程序。
```

i can also run tenosrrt model in older version of tensorrt and yolov5
```
(yolo) D:\AIII\test\yolov5-master(original)\yolov5-master>python detect.py --source "D:\AIII\Yolov5_StrongSORT_OSNet-master\Desktop 2022.11.08 - 20.02.31.01.mp4" --weights "D:\AIII\test\yolov5-master(original)\yolov5-master\runs\tra
in\354exp9\weights\best.engine" --imgsz 1056 --view-img --device 0
detect: weights=['D:\\AIII\\test\\yolov5-master(original)\\yolov5-master\\runs\\train\\354exp9\\weights\\best.engine'], source=D:\AIII\Yolov5_StrongSORT_OSNet-master\Desktop 2022.11.08 - 20.02.31.01.mp4, data=data\coco128.yaml, imgs
z=[1056, 1056], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=0, view_img=True, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, 
project=runs\detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5  2022-9-21 Python-3.7.13 torch-1.12.1 CUDA:0 (NVIDIA GeForce RTX 3070 Laptop GPU, 8192MiB)

Loading D:\AIII\test\yolov5-master(original)\yolov5-master\runs\train\354exp9\weights\best.engine for TensorRT inference...
[11/09/2022-13:04:41] [TRT] [I] [MemUsageChange] Init CUDA: CPU +451, GPU +0, now: CPU 7855, GPU 1201 (MiB)
[11/09/2022-13:04:42] [TRT] [I] Loaded engine size: 30 MiB
[11/09/2022-13:04:43] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +1031, GPU +396, now: CPU 8977, GPU 1627 (MiB)
[11/09/2022-13:04:43] [TRT] [W] TensorRT was linked against cuDNN 8.4.1 but loaded cuDNN 8.3.2
[11/09/2022-13:04:43] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
[11/09/2022-13:04:43] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 8954, GPU 1629 (MiB)
[11/09/2022-13:04:43] [TRT] [W] TensorRT was linked against cuDNN 8.4.1 but loaded cuDNN 8.3.2
[11/09/2022-13:04:43] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
video 1/1 (1/365) D:\AIII\Yolov5_StrongSORT_OSNet-master\Desktop 2022.11.08 - 20.02.31.01.mp4: 1056x1056 2 persons, 2 bicycles, 7.0ms
```

### Environment

- OS: Windows10 21H2
- Python: 3.10
- tensorRT: 8.5.1.7
- cuda: nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:59:34_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0
- torch: 1.13.0

### Minimal Reproducible Example

```
python ./yolov5/detect.py --weights ./weights/best.engine --source "Desktop 2022.11.08 - 20.02.31.01.mp4" --imgsz 1056 --view-img
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment] 2022-11-09 14:41
@Need-an-AwP 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. TensorRT exports and predicts correctly in my test just now in Colab. I'm not able to reproduce any TRT-related issues.

<img width="1680" alt="Screenshot 2022-11-09 at 15 40 49" src="https://user-images.githubusercontent.com/26833433/200859861-f2e58dd6-3e97-4646-b78c-1cd3aaa23315.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Closed as completed** 2022-11-10 17:06 UTC
Labels: bug

**Comment by xqh5201314** [comment] 2022-11-26 09:04
do you save this problem？i meet  this too.

**Comment by Need-an-AwP** [comment] 2022-12-02 09:00
> do you save this problem？i meet this too.

use a new environment with the latest version of tensorrt, cuda and pytorch
I still dont know what cause this problem, so the only thing i can do is rebuilt and retrain my model, then export it to onnx and engine files with the complete new environment
(i guess the different of tensorrt version made this problem)

**Comment by glenn-jocher** [comment] 2023-11-15 14:49
@Need-an-AwP i understand your frustration and appreciate your efforts to troubleshoot the issue. It's possible that differences in the TensorRT version could indeed be causing this problem. Rebuilding and retraining the model with a new environment and exporting it to ONNX and engine files sounds like a reasonable approach to resolve the issue. If you encounter any further difficulties or have additional questions, feel free to reach out for assistance. Good luck with your model retraining!
