### ISSUE TITLE
Detect.py seems to give error on .mpg video format file

### ISSUE THREAD

**Issue by THINK989** [ultralytics/yolov5#146] opened 2020-06-20 16:14 UTC
Hello Everyone,
First of all, this is a great repository. Now right to the point, I tried to test the model on my video file which has an extension of .mpg. It doesn't work and gives me an error. I don't feel my file is corrupted since it works on Yolov3 and Yolov4 which I know are darknet versions. I also tried on OpenCV and it works.

I typed the following command:-
```
 python detect.py  --source input.mpg --view-img
```

and got the following error:-
```
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='0', fourcc='mp4v', img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='input.mpg', view_img=True, weights='weights/yolov5s.pt')
Using CUDA device0 _CudaDeviceProperties(name='GeForce GTX 1050', total_memory=4096MB)

Traceback (most recent call last):
  File "detect.py", line 158, in <module>
    detect()
  File "detect.py", line 45, in detect
    dataset = LoadImages(source, img_size=imgsz)
  File "D:\github\Automatic_License_Plate_Detector_and_Recognizer\yolov5\utils\datasets.py", line 66, in __init__
    assert self.nF > 0, 'No images or videos found in ' + path
AssertionError: No images or videos found in input.mpg

```

Requirements:-
```
python==3.7.6
torch==1.5.0
numpy==1.18.5
```

If anyone is able to run detect.py on a .mpg file, please help on why it is not working for me.

**Comment by glenn-jocher** [comment] 2020-06-20 16:22
@THINK989 thank you for the your bug report. We are able to reproduce this using an example video http://mirrors.standaloneinstaller.com/video-sample/P6090053.mpg in colab.

I'll see what the problem is.

**Comment by glenn-jocher** [comment] 2020-06-20 16:24
It seems this is simply not in the list of video formats to search for. I'll add the mpg extension to the video list. Ok, everything is resolved now. I will push a fix for this shortly and backpropagate the fix to our yolov3 repo as well.

<img width="920" alt="Screen Shot 2020-06-20 at 9 24 16 AM" src="https://user-images.githubusercontent.com/26833433/85206569-ef41c880-b2d7-11ea-810a-53d4c14d7566.png">

**Closed as completed** 2020-06-20 16:26 UTC
Labels: bug

**Comment by glenn-jocher** [comment] 2020-06-20 16:27
@THINK989 all done, fix has been pushed, please git pull to receive update. The full list of compatible formats is here, are there any others you think we might be missing?

https://github.com/ultralytics/yolov5/blob/5c2cd711df6099aa56b57bbb62381862cfcf9f18/utils/datasets.py#L20-L21

**Comment by THINK989** [comment] 2020-06-20 18:55
Thank You @glenn-jocher. Great Work on the repository.
