### ISSUE TITLE
F-1 Score

### ISSUE THREAD

**Issue by wanterlim** [ultralytics/yolov5#1502] opened 2020-11-25 07:09 UTC
## ❔Question
I read my results training, but i can't find the F-1 Score that featured in YOLOv3 and V4, how can i compute the F-1 Score?
Thank you for reaching this question

**Comment by glenn-jocher** [comment] 2020-11-25 08:57
@wanterlim F1 is computed and sent to test.py here, though it is no longer displayed to screen as you mentioned.
https://github.com/ultralytics/yolov5/blob/2026d4c5eb4e3e48b5295106db85c844000d95d1/utils/metrics.py#L70-L77

**Comment by wanterlim** [comment] 2020-11-25 11:33
So, if i want to know my f1 score training, i need to retrain my dataset? or by calling metrics.py function? Can you be more specific how to get my f1 score?

**Comment by glenn-jocher** [comment] 2020-11-25 11:35
@wanterlim no you don't need to retrain anything, you just run test.py on your model. F1 score is already computed and exported and available in test().

**Comment by wanterlim** [comment] 2020-11-25 17:54
> @wanterlim no you don't need to retrain anything, you just run test.py on your model. F1 score is already computed and exported and available in test().

I tried this code in Colab. 
![image](https://user-images.githubusercontent.com/63143827/100264613-a296a380-2f81-11eb-9a71-2aba9c78cb43.png)
But there are some errors as this picture 
![image](https://user-images.githubusercontent.com/63143827/100264741-d376d880-2f81-11eb-8e6d-40f9e76b9043.png).
Is there something wrong with my code?

**Comment by glenn-jocher** [comment] 2020-11-25 18:33
@wanterlim ah, thanks for spotting this. Seems to be a bug in master. I will review.

**Comment by glenn-jocher** [comment] 2020-11-25 18:39
Bug report is duplicate of 1508, will move bug convo over there.

**Comment by glenn-jocher** [comment] 2020-11-25 19:33
@wanterlim This should be resolved in PR #1513. Please git pull and try again.

**Closed as completed** 2020-11-25 19:33 UTC
Labels: duplicate, question
