### ISSUE TITLE
yolov5 --save-crop unable to save every detection

### ISSUE THREAD

**Issue by Andy31798** [ultralytics/yolov5#7432] opened 2022-04-15 07:32 UTC
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Hello.
I have been trying to save the predicted box from the image I passed into the detect.py. 

In my case, detect.py is able to detect 5 junctions as shown in the pictures below.
![image](https://user-images.githubusercontent.com/103730990/163538191-7c5381fc-342e-4916-be1a-00bc2a90d04e.png)

![image](https://user-images.githubusercontent.com/103730990/163538321-ac43fad3-098f-4521-a041-a9e98cceedf6.png)

However, the cropped images saved for junctions detected are just 2 instead of 5. 
![image](https://user-images.githubusercontent.com/103730990/163538257-f230e8a0-2863-4bf5-aa69-bfe9398b24f6.png)

The detect.py code that I'm using
![image](https://user-images.githubusercontent.com/103730990/163550089-9ffca555-012b-4fc1-9bd6-40ff0a05d259.png)

Can anyone provide help with this?

Thank you

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment] 2022-04-15 19:51
@Andy31798 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Andy31798** [comment] 2022-04-16 07:09
@glenn-jocher Hi. Thank you for your reply.
I have figured out the cause of my problem. It's due to the naming of my filename that makes the code confuse and cannot proceed with path increment.

**Comment by glenn-jocher** [comment] 2022-04-16 13:11
@Andy31798 got it. The path increment function is here:
https://github.com/ultralytics/yolov5/blob/3eefab1bb109214a614485b6c5f80f22c122f2b2/utils/general.py#L928-L941

Take a look and see if there any improvements that could be made to accommodate your use case. 

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by 6630507** [comment] 2022-04-28 16:40
I had the same problem as @Andy31798.  I only would have figured this out by accident had I not stumbled across this thread.

Yolo was only saving crops from a random 2 matches out of 12-15 per image.  When I renamed my files (from "default.jpg.30.jpg" to "devisesetembleme00lafeu_00014.jpg"), --save-crop worked as expected.

One strange caveat.  The files --crop-save outputs have inconsistent padding around the numbers.  For example, after my run, I get files like:

devisesetembleme00lafeu_00012.jpg
devisesetembleme00lafeu_000012.jpg
devisesetembleme00lafeu_00013.jpg
devisesetembleme00lafeu_000013.jpg

They are not duplicates; I checked a few, and there are the correct number of matches in my output folder.

**Comment by glenn-jocher** [comment] 2022-04-28 20:19
@6630507 @Andy31798 it looks like `increment_path()` might need some work. I wrote this from the ground up just for this task because I couldn't find an off the shelf solution, so it's probably not as mature of a solution as it should be.

**Comment by glenn-jocher** [comment] 2022-04-28 21:01
@6630507 @Andy31798 good news 😃! Your original issue may now be fixed ✅ in PR #7628. This PR improves path incrementing for edge case paths as shown in this bug report.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Closed as completed** 2022-04-28 21:00 UTC
Labels: bug

**Comment by 6630507** [comment] 2022-04-29 15:02
Awesome, thanks!

**Comment by glenn-jocher** [comment] 2023-11-15 15:06
@6630507 you're welcome! If you have any more questions or need further assistance, feel free to ask. Happy detecting with YOLOv5! 🚀
