### ISSUE TITLE
wandbutils.py line 161 AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by markgicharu** [ultralytics/yolov5#2674] opened 2021-03-31 20:55 UTC
## Additional context
Traceback (most recent call last):
  File "train.py", line 541, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 72, in train
    wandb_logger = WandbLogger(opt, Path(opt.save_dir).stem, run_id, data_dict)
  File "C:\Users\markg\venv\yolov5\utils\wandb_logging\wandb_utils.py", line 109, in __init__
    self.data_dict = self.setup_training(opt, data_dict)
  File "C:\Users\markg\venv\yolov5\utils\wandb_logging\wandb_utils.py", line 140, in setup_training
    self.train_artifact_path, self.train_artifact = self.download_dataset_artifact(data_dict.get('train'),
  File "C:\Users\markg\venv\yolov5\utils\wandb_logging\wandb_utils.py", line 161, in download_dataset_artifact
    if path.startswith(WANDB_ARTIFACT_PREFIX):
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by glenn-jocher** [comment] 2021-04-01 12:21
@markgicharu hi sorry about that. This may be related to a recent update we did with W&B and @AyushExel.

If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!

**Comment by AyushExel** [comment] 2021-04-01 12:31
Looking. It should be a typo. I'll push a fix

**Comment by AyushExel** [comment] 2021-04-01 12:39
@markgicharu Can you share the data.yaml file that you're passing with `--data` argument? I think either the train or val path is empty that's why `data_ditc['val or train']` results as NoneType.

@glenn-jocher what should be the behaviour here, should we allow users to train without having a val set?

**Comment by AyushExel** [comment] 2021-04-01 12:46
@glenn-jocher @markgicharu Okay I reproduced this issue with coco128 dataset. If I comment out the the val path like this:
```
train: ../coco128/images/train2017/  # 128 images
#val: ../coco128/images/train2017/  # 128 images
```
But even on disabling wandb, it throws an error:
```
Traceback (most recent call last):
  File "train.py", line 541, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 99, in train
    test_path = data_dict['val']
KeyError: 'val'
```
I think the desired behavior is to not allow users to only pass the train set without passing val set. What should I do here? Even on pushing a fix for this, wandb_utils won't throw an error but the above error will still be there

**Comment by glenn-jocher** [comment] 2021-04-01 15:05
@AyushExel training requires a val set. I think normally this error would be caught in the dataloader in either L368, L371, L373 and the message explains the cause well. If the error is caused earlier now then I suppose a similar assert statement might be reasonable to explain to the user the problem (as often the error message is hard for the user to connect to the cause of the error).
https://github.com/ultralytics/yolov5/blob/b8b862993d8e0a267f7d96eb94307f3f0f7dce51/utils/datasets.py#L355-L374

@markgicharu you need to fully populate the train and val fields in your dataset.yaml as the **Train Custom Data** Tutorial shows. Please see this tutorial to get started. If you have no val set you can re-use your training set to validate on (as the COCO128 training does), though this is usually only used for sanity checks and is not best practices.

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [ONNX and TorchScript Export](https://docs.ultralytics.com/yolov5/tutorials/model_export)
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by AyushExel** [comment] 2021-04-01 16:22
This should address the problem #2683

**Closed as completed** 2021-04-02 09:54 UTC
Labels: question

**Comment by markgicharu** [comment] 2021-04-03 19:50
> @markgicharu Can you share the data.yaml file that you're passing with `--data` argument? I think either the train or val path is empty that's why `data_ditc['val or train']` results as NoneType.
> 
> @glenn-jocher what should be the behaviour here, should we allow users to train without having a val set?

Hello @AyushExel 
Am sharing the data.yaml below:
I tried checking the paths to see if there is any issue. Maybe you can advise best from the file below.
I have split my dataset in train, validate and test in a 70-20-10 split.
[data.yaml.zip](https://github.com/ultralytics/yolov5/files/6253296/data.yaml.zip)

**Comment by markgicharu** [comment] 2021-04-03 19:52
> @markgicharu hi sorry about that. This may be related to a recent update we did with W&B and @AyushExel.
> 
> If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!

@glenn-jocher Many thanks for the prompt response
I will push it to a bug as suggested
Apologies for the late response. Been up and down during Easter. AM back settled now.
Thanks again

**Comment by glenn-jocher** [comment] 2021-04-05 09:42
@markgicharu this problem may have been fixed recently in PR #2683. Can you please git pull or reclone and try again to see if the issue is resolved? Thank you!

**Comment by markgicharu** [comment] 2021-04-05 10:22
@glenn-jocher This matter is resolved
When i pass the absolute path for the train and test in the data.yaml the system works well.
Many thanks for the prompt response.

**Comment by glenn-jocher** [comment] 2021-04-05 10:44
@markgicharu great! Happy trainings.

**Comment by anupkumar08** [comment] 2023-06-19 18:10
while executing 
%cd /content/yolov5/
!python test.py --data '../data.yaml' --img 416 --conf 0.40  --weights 'path to weights'

In Colab. I am facing issue:

/content/yolov5
Namespace(weights=['path to weights'], data='../data.yaml', batch_size=32, img_size=416, conf_thres=0.4, iou_thres=0.6, task='val', device='', single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project='runs/test', name='exp', exist_ok=False)
YOLOv5 🚀 v7.0-185-g2334aa7 torch 2.0.1+cu118 CUDA:0 (Tesla T4, 15101.8125MB)

Traceback (most recent call last):
  File "/content/yolov5/test.py", line 316, in <module>
    test(opt.data,
  File "/content/yolov5/test.py", line 54, in test
    (save_dir / 'labels' if save_txt else save_dir).mkdir(parents=True, exist_ok=True)  # make dir
AttributeError: 'NoneType' object has no attribute 'mkdir'

**Comment by glenn-jocher** [comment] 2023-11-15 01:57
@anupkumar08 it looks like the issue you are facing might be related to the way you are specifying the weights path or data path. The current error message suggests that there might be a problem related to saving directories. 

Make sure that you have provided the correct path to the weights file and the data.yaml file. Also, ensure that the data.yaml file is correctly formatted with the paths to your dataset, and the weights path is pointing to a valid location.

If the issue persists, please consider opening a new issue on the YOLOv5 GitHub repository, providing a detailed description of the problem along with the command you used, and any relevant code or configuration files. This will allow the community to better understand and assist with your specific situation.
