### ISSUE TITLE
python detect.py on jetson nano ..RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same

### ISSUE THREAD

**Issue by DENESTY** [ultralytics/yolov5#78] opened 2020-06-15 22:37 UTC
Traceback (most recent call last):
  File "detect.py", line 163, in <module>
    detect()
  File "detect.py", line 54, in detect
    _ = model(img.half() if half else img.float()) if device.type != 'cpu' else None  # run once
  File "/home/z/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/z/yolov5/models/yolo.py", line 91, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/home/z/yolov5/models/yolo.py", line 108, in forward_once
    x = m(x)  # run
  File "/home/z/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/z/yolov5/models/common.py", line 86, in forward
    return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
  File "/home/z/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/z/yolov5/models/common.py", line 21, in forward
    return self.act(self.bn(self.conv(x)))
  File "/home/z/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/z/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 349, in forward
    return self._conv_forward(input, self.weight)
  File "/home/z/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 346, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same

 inference yolov5s.pt  on jetson nano is successfully ，but yolov5m,l,x.pt is failed,the error is shown above,how to solve it???

**Comment by DENESTY** [comment] 2020-06-15 22:41
Python3.6  pytorch1.15

**Comment by glenn-jocher** [comment] 2020-06-15 22:52
@DENESTY all models are now natively stored in FP16, and detect.py will use mixed precision inference whenever the cpu is not used. You can force FP32 inference if you'd like here:
https://github.com/ultralytics/yolov5/blob/0b514daced65d8c44dbf9f6f6bfa9ca2a1de7324/detect.py#L17

Though I would reclone a new copy of the repo, as it is changing quickly, so your problem may already no longer exist in the latest code.

**Comment by xiaoyangstat** [comment] 2020-07-05 14:34
> @DENESTY all models are now natively stored in FP16, and detect.py will use mixed precision inference whenever the cpu is not used. You can force FP32 inference if you'd like here:
> https://github.com/ultralytics/yolov5/blob/0b514daced65d8c44dbf9f6f6bfa9ca2a1de7324/detect.py#L17
> 
> Though I would reclone a new copy of the repo, as it is changing quickly, so your problem may already no longer exist in the latest code.

Since `all models are now natively stored in FP16`, will we lose some information if we do `model.float()` comparing to the weights originally stored in FB32?

**Comment by glenn-jocher** [comment] 2020-07-05 16:37
mAP is not affected

**Comment by mary-0830** [comment] 2020-07-16 04:47
> Traceback (most recent call last):
> File "detect.py", line 163, in
> detect()
> File "detect.py", line 54, in detect
> _ = model(img.half() if half else img.float()) if device.type != 'cpu' else None # run once
> File "/home/z/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/z/yolov5/models/yolo.py", line 91, in forward
> return self.forward_once(x, profile) # single-scale inference, train
> File "/home/z/yolov5/models/yolo.py", line 108, in forward_once
> x = m(x) # run
> File "/home/z/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/z/yolov5/models/common.py", line 86, in forward
> return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
> File "/home/z/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/z/yolov5/models/common.py", line 21, in forward
> return self.act(self.bn(self.conv(x)))
> File "/home/z/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/z/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 349, in forward
> return self._conv_forward(input, self.weight)
> File "/home/z/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 346, in _conv_forward
> self.padding, self.dilation, self.groups)
> RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same
> 
> inference yolov5s.pt on jetson nano is successfully ，but yolov5m,l,x.pt is failed,the error is shown above,how to solve it???

I have the same question.How do you solve it?

**Comment by glenn-jocher** [comment] 2020-07-16 05:06
Make sure you are using the latest code, this is an old bug that has been fixed.

**Comment by mary-0830** [comment] 2020-07-16 05:55
> Make sure you are using the latest code, this is an old bug that has been fixed.

**Yes, I have updated the latest code and still report this error.**

```
Traceback (most recent call last):
  File "detect.py", line 162, in <module>
    detect()
  File "detect.py", line 53, in detect
    _ = model(img.half() if half else img) if device.type != 'cpu' else None  # run once
  File "/sujh/env/env_yolov3_torch/lib/python3.5/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jjliao/code/yolov5/models/yolo.py", line 95, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/home/jjliao/code/yolov5/models/yolo.py", line 115, in forward_once
    x = m(x)  # run
  File "/sujh/env/env_yolov3_torch/lib/python3.5/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jjliao/code/yolov5/models/common.py", line 92, in forward
    return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
  File "/sujh/env/env_yolov3_torch/lib/python3.5/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jjliao/code/yolov5/models/common.py", line 30, in fuseforward
    return self.act(self.conv(x))
  File "/sujh/env/env_yolov3_torch/lib/python3.5/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/sujh/env/env_yolov3_torch/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 349, in forward
    return self._conv_forward(input, self.weight)
  File "/sujh/env/env_yolov3_torch/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 346, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.HalfTensor) should be the same
```

**Comment by glenn-jocher** [comment] 2020-07-16 16:21
@mary-0830 your issue seems to lack the minimum requirements for a proper response, or is insufficiently detailed for us to help you. Please note that most technical problems are due to:

- **Your changes to the default repository**. If your issue is not reproducible in a fresh `git clone` version of this repository we can not debug it. Before going further run this code and ensure your issue persists:
```bash
sudo rm -rf yolov5  # remove existing
git clone https://github.com/ultralytics/yolov5 && cd yolov5 # clone latest
python detect.py  # verify detection
python train.py  # verify training (a few batches only)
# CODE TO REPRODUCE YOUR ISSUE HERE
```
- **Your custom data.** If your issue is not reproducible with COCO data we can not debug it. Visit our [Custom Training Tutorial](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) for guidelines on training your custom data. Examine `train_batch0.jpg` and `test_batch0.jpg` for a sanity check of training and testing data.
- **Your environment.** If your issue is not reproducible in our [Google Cloud](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) VM or Jupyter Notebook we can not debug it. Ensure you meet the requirements specified in the README: Unix, MacOS, or Windows with Python >= 3.7, PyTorch >= 1.5 etc. You can also use our [Jupyter Notebook](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb) <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> and our [Docker Image](https://hub.docker.com/r/ultralytics/yolov5) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker) to test your code in a working environment.

If none of these apply to you, we suggest you close this issue and raise a new one using the **Bug Report template**, providing screenshots and **minimum viable code to reproduce your issue**. Thank you!

**Closed as completed** 2020-07-16 16:21 UTC
