### ISSUE TITLE
using two yolo models

### ISSUE THREAD

**Issue by nebiyebln** [ultralytics/yolov5#4740] opened 2021-09-10 11:39 UTC
I trained my own dataset with yolov5 using google colab. I made a license plate recognition system. But it can't read the letters exactly. tesseract is not enough for this. can I train another model with letters and numbers again using yolo? how do you think this is. is it a good idea? please let me know about it....

**Comment by glenn-jocher** [comment] 2021-09-10 12:54
@nebiyebln duplicate of #4738

**Closed as completed by glenn-jocher** 2021-09-10 12:54 UTC
Labels: duplicate, question
