### ISSUE TITLE
The speed of the conference is different between Windows and Ubuntu.The speed of the conference is different between Windows and Ubuntu.

### ISSUE THREAD

**Issue by hi-one-gg** [ultralytics/yolov5#5473] opened 2021-11-03 11:23 UTC
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

A PC : windows10+Quadro RTX 8000+ssd, cuda10.1.105, cudnn 7.6.5, torch7.0, yolov5-5.0
B PC : ubuntu18.04+Quadro RTX 8000+ssd, cuda10.1.105, cudnn 7.6.5, torch7.0, yolov5-5.0

Inference Speed on windows10 : about 34FPS (my custom model, same code)
Inference Speed on ubuntu18.04 : about 50FPS (my custom mode, same code)

Why is this difference happening? WHY??

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment] 2021-11-03 13:12
@blackCmd I don't know why you would raise a bug report here. Bug reports are to solve errors that occur that are caused by YOLOv5. If you have a reproducible error then please submit a bug report. Closing issue.

**Closed as completed by glenn-jocher** 2021-11-03 13:12 UTC
Labels: bug
