### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Laudarisd** [ultralytics/yolov5#3257] opened 2021-05-20 09:27 UTC
## ❔Question

Hello @glenn-jocher  really appreciate your time for reviewing our questions.

I got one problem while using following command:
```python3 detect.py --source ./test/ --weights ./best.pt --conf 0.25 --save-txt```

And problem is:

```
Model Summary: 392 layers, 46600566 parameters, 0 gradients
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
image 1/1051 /AI/AI/mapillary_AI/pytorch_yolo/test/1.png: Traceback (most recent call last):
  File "detect.py", line 186, in <module>
    detect(opt=opt)
  File "detect.py", line 101, in detect
    s += f"{n} {names[int(c)]}{'s' * (n > 1)}, "  # add to string
IndexError: list index out of range
```

I am using Docker , and I am training my own custom dataset. 

While running training its' fine but I am getting error while doing inference.

Is it because of python version??

Thank you so much.

**Comment by glenn-jocher** [comment] 2021-05-20 12:50
@Laudarisd If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose), providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Closed as completed** 2021-05-20 23:56 UTC
Labels: question

**Comment by NaragintiChanduPriya** [comment] 2023-04-23 11:53
> ## ❔Question
> Hello @glenn-jocher really appreciate your time for reviewing our questions.
> 
> I got one problem while using following command: `python3 detect.py --source ./test/ --weights ./best.pt --conf 0.25 --save-txt`
> 
> And problem is:
> 
> ```
> Model Summary: 392 layers, 46600566 parameters, 0 gradients
> /usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
>   return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
> image 1/1051 /AI/AI/mapillary_AI/pytorch_yolo/test/1.png: Traceback (most recent call last):
>   File "detect.py", line 186, in <module>
>     detect(opt=opt)
>   File "detect.py", line 101, in detect
>     s += f"{n} {names[int(c)]}{'s' * (n > 1)}, "  # add to string
> IndexError: list index out of range
> ```
> 
> I am using Docker , and I am training my own custom dataset.
> 
> While running training its' fine but I am getting error while doing inference.
> 
> Is it because of python version??
> 
> Thank you so much.
> 
> ## Additional context

did u resolved your problem???
I too get same problem??
can you please tell what to do??

**Comment by NaragintiChanduPriya** [comment] 2023-04-23 11:59
model Summary: 224 layers, 7266973 parameters, 0 gradients, 0.7 GFLOPs
image 1/1 C:\Users\chandu\OneDrive\Desktop\yolo\yolov5\instance\uploads\WIN_20220507_16_52_04_Pro.jpg: Traceback (most recent call last):
  File "C:\Users\chandu\OneDrive\Desktop\yolo\yolov5\detect.py", line 238, in <module>
    main(opt)
  File "C:\Users\chandu\OneDrive\Desktop\yolo\yolov5\detect.py", line 233, in main
    run(**vars(opt))
  File "C:\Users\chandu\AppData\Roaming\Python\Python310\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\chandu\OneDrive\Desktop\yolo\yolov5\detect.py", line 146, in run
    s += f"{n} {names[int(c)]}{'s' * (n > 1)}, "  # add to string
IndexError: list index out of range
127.0.0.1 - - [23/Apr/2023 17:19:42] "POST /detect HTTP/1.1" 200 -
..................................................................................................................................................................................................................................
am getting error like this???

**Comment by glenn-jocher** [comment] 2023-04-23 15:55
@NaragintiChanduPriya 

The error `IndexError: list index out of range` is usually due to a problem with the object indexing. The specific line where the error is happening is when printing out the predicted class.

You may find the error more easily if you modify the source code to print the values of "c" and "names" at the point where the error occurs.

There are several potential causes, including input issues, model configuration or corrupted data. We recommend that you double-check that all requirements for using YOLOv5 are installed properly and that your data is in the correct format. Also, ensure that your dataset has objects and annotations correctly presented.

If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose), providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!
