### ISSUE TITLE
Can't get attribute 'C3' on <module 'models.common' while loading yolov5s

### ISSUE THREAD

**Issue by kaushalchapaneri-intellica** [ultralytics/yolov5#1855] opened 2021-01-06 13:38 UTC
## ❔Question
I am trying to load small model of yolo v5 with following steps:

import torch

torch.load('yolov5s.pt')

but getting error AttributeError: Can't get attribute 'C3' on <module 'models.common' from '/yolov5/models/common.py'>

## Additional context
i am using ubuntu 18.04
torch == 1.7.1
python = 3.8.0
please let me know if additional information is needed.

**Comment by glenn-jocher** [comment] 2021-01-07 00:06
@kaushalchapaneri-intellica your code is likely out of date. You should `git pull` to update it or reclone the repo.

**Comment by Lnazvkl** [comment] 2021-01-13 11:38
> @kaushalchapaneri-intellica your code is likely out of date. You should `git pull` to update it or reclone the repo.

hi, while I want to train yolov5 on custom dataset I got this error: 

Traceback (most recent call last):
  File "train.py", line 404, in <module>
    train(hyp)
  File "train.py", line 80, in train
    model = Model(opt.cfg).to(device)
  File "/content/yolov5/models/yolo.py", line 57, in __init__
    self.model, self.save = parse_model(self.md, ch=[ch])  # model, savelist, ch_out
  File "/content/yolov5/models/yolo.py", line 153, in parse_model
    m = eval(m) if isinstance(m, str) else m  # eval strings
  File "<string>", line 1, in <module>
NameError: name 'C3' is not defined

it happens when I use lastest yolov5x.yaml file which containes:
backbone:
  # [from, number, module, args]
  [[-1, 1, Focus, [64, 3]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 9, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 1, SPP, [1024, [5, 9, 13]]],
   [-1, 3, C3, [1024, False]],  # 9
  ]

I don't know how to solve it, I will be appreciated if you help me.

**Comment by glenn-jocher** [comment] 2021-01-13 17:09
@Lnazvkl your code is out of date. Use `git pull` to update your code, or simply `git clone https://github.com/ultralytics/yolov5` to download a new copy.

**Comment by Lnazvkl** [comment] 2021-01-13 17:15
> @Lnazvkl your code is out of date. Use `git pull` to update your code, or simply `git clone https://github.com/ultralytics/yolov5` to download a new copy.

I had updated, but I have got this error after update.

**Comment by glenn-jocher** [comment] 2021-01-13 17:23
@Lnazvkl the error you are seeing is due to **out of date or modified code**. To start simply clone a fresh copy of the repo, and verify training for a few epochs. 
```bash
git clone https://github.com/ultralytics/yolov5
cd yolov5
python train.py --epochs 3
```

Alternatively you can start from the official notebook (3rd party notebooks are not supported):
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

**Comment by glenn-jocher** [comment] 2021-01-13 17:24
@Lnazvkl I will also post our full response with additional details that may help you. Please note that most technical problems are due to:

- **Your modified or out-of-date code**. If your issue is not reproducible in a new `git clone` version of this repo we can not debug it. Before going further run this code and verify your issue persists:
```bash
$ git clone https://github.com/ultralytics/yolov5 yolov5_new  # clone latest
$ cd yolov5_new
$ python detect.py  # verify detection

# CODE TO REPRODUCE YOUR ISSUE HERE
```

- **Your custom data.** If your issue is not reproducible in one of our 3 common datasets ([COCO](https://github.com/ultralytics/yolov5/blob/master/data/coco.yaml), [COCO128](https://github.com/ultralytics/yolov5/blob/master/data/coco128.yaml), or [VOC](https://github.com/ultralytics/yolov5/blob/master/data/voc.yaml)) we can not debug it. Visit our [Custom Training Tutorial](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) for guidelines on training your custom data. Examine `train_batch0.jpg` and `test_batch0.jpg` for a sanity check of your labels and images.

- **Your environment.** If your issue is not reproducible in one of the verified environments below we can not debug it. If you are running YOLOv5 locally, verify your environment meets all of the [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies specified below. If in doubt, download Python 3.8.0 from https://www.python.org/, create a new [venv](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/), and install requirements.

If none of these apply to you, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and **minimum viable code to reproduce your issue**. Thank you!


## Requirements

Python 3.8 or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including `torch>=1.7`. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by Lnazvkl** [comment] 2021-01-13 19:31
> @Lnazvkl I will also post our full response with additional details that may help you. Please note that most technical problems are due to:
> 
> * **Your modified or out-of-date code**. If your issue is not reproducible in a new `git clone` version of this repo we can not debug it. Before going further run this code and verify your issue persists:
> 
> ```shell
> $ git clone https://github.com/ultralytics/yolov5 yolov5_new  # clone latest
> $ cd yolov5_new
> $ python detect.py  # verify detection
> 
> # CODE TO REPRODUCE YOUR ISSUE HERE
> ```
> 
> * **Your custom data.** If your issue is not reproducible in one of our 3 common datasets ([COCO](https://github.com/ultralytics/yolov5/blob/master/data/coco.yaml), [COCO128](https://github.com/ultralytics/yolov5/blob/master/data/coco128.yaml), or [VOC](https://github.com/ultralytics/yolov5/blob/master/data/voc.yaml)) we can not debug it. Visit our [Custom Training Tutorial](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) for guidelines on training your custom data. Examine `train_batch0.jpg` and `test_batch0.jpg` for a sanity check of your labels and images.
> * **Your environment.** If your issue is not reproducible in one of the verified environments below we can not debug it. If you are running YOLOv5 locally, verify your environment meets all of the [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies specified below. If in doubt, download Python 3.8.0 from https://www.python.org/, create a new [venv](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/), and install requirements.
> 
> If none of these apply to you, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and **minimum viable code to reproduce your issue**. Thank you!
> 
> ## Requirements
> Python 3.8 or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including `torch>=1.7`. To install run:
> 
> ```shell
> $ pip install -r requirements.txt
> ```
> 
> ## Environments
> YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):
> 
> * **Google Colab Notebook** with free GPU: [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb)
> * **Kaggle Notebook** with free GPU: https://www.kaggle.com/models/ultralytics/yolov5
> * **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
> * **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://camo.githubusercontent.com/280faedaf431e4c0c24fdb30ec00a66d627404e5c4c498210d3f014dd58c2c7e/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f796f6c6f76353f6c6f676f3d646f636b6572)
> 
> ## Status
> ![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)
> 
> If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

as you said I update yolov5 but I got these errors:
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
python3: can't open file 'detect.py': [Errno 2] No such file or directory

![image](https://user-images.githubusercontent.com/36161946/104500060-27518580-55f3-11eb-9b5b-467c026dcdfd.png)

special thanks for your attention.

**Comment by glenn-jocher** [comment] 2021-01-13 19:37
@Lnazvkl I don't recognize the notebook you are using. There are many 3rd party notebooks that we do not support and that may have performance issues. I would recommend you simply start from the official YOLOv5 notebook, which is authored by Ultralytics and verified working correctly:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

To train with the official notebook, you simply click the Setup cell, and then run the Train cell. Two clicks gets you training correctly.
<img width="1243" alt="Screen Shot 2021-01-13 at 11 36 05 AM" src="https://user-images.githubusercontent.com/26833433/104500734-a44d1280-5593-11eb-9886-85915ade877b.png">

**Comment by Lnazvkl** [comment] 2021-01-13 19:54
> @Lnazvkl I don't recognize the notebook you are using. There are many 3rd party notebooks that we do not support and that may have performance issues. I would recommend you simply start from the official YOLOv5 notebook, which is authored by Ultralytics and verified working correctly:
> https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb
> 
> To train with the official notebook, you simply click the Setup cell, and then run the Train cell. Two clicks gets you training correctly.
> <img alt="Screen Shot 2021-01-13 at 11 36 05 AM" width="1243" src="https://user-images.githubusercontent.com/26833433/104500734-a44d1280-5593-11eb-9886-85915ade877b.png">

I am using google colab.

**Comment by glenn-jocher** [comment] 2021-01-13 19:59
@Lnazvkl you are using an unsupported notebook in google colab. The official Ultralytics YOLOv5 notebook is here:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

**Closed as completed by glenn-jocher** 2021-01-13 19:59 UTC
Labels: question

**Comment by Lnazvkl** [comment] 2021-01-13 20:01
> @Lnazvkl you are using an unsupported notebook in google colab. The official Ultralytics YOLOv5 notebook is here:
> https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

thanks for your response.

**Comment by cs-heibao** [comment] 2021-03-16 03:58
@kaushalchapaneri-intellica 
I've meet the same error(just use torch to torch.load('yolov5s.pt'))
`AttributeError: Can't get attribute 'C3' on <module 'models.common' '>`

**Comment by kaushalchapaneri-intellica** [comment] 2021-03-16 04:54
@cs-heibao try this: 

step 1 : re clone repo in different folder by `git clone https://github.com/ultralytics/yolov5.git`
step 2 :  `cd yolov5`
step 3 : then run `python detect.py --source data/images/bus.jpg`  (assuming your python environment has all the dependencies mentioned [here](https://github.com/ultralytics/yolov5#requirements))

now on python terminal or in .py file run this:

`import torch`
`torch.load('yolov5s.pt')`
