### ISSUE TITLE
problem when using multi GPU

### ISSUE THREAD

**Issue by Xiaocong6** [ultralytics/yolov5#2814] opened 2021-04-16 11:04 UTC
## When I use multi-GPU training, I will stop at this place without reporting any errors. What is the reason? Thanks!
![image](https://user-images.githubusercontent.com/44869509/115015670-9b4b4480-9ee6-11eb-973f-0caa1599e33e.png)

**Comment by glenn-jocher** [comment] 2021-04-16 19:47
@Xiaocong6 👋 Hello, thank you for your interest in our work! This issue seems to lack the minimum requirements for a proper response, or is insufficiently detailed for us to help you. Please note that most technical problems are due to:

- **Your modified or out-of-date code**. If your issue is not reproducible in a new `git clone` version of this repo we can not debug it. Before going further run this code and verify your issue persists:
```bash
$ git clone https://github.com/ultralytics/yolov5 yolov5_new  # clone latest
$ cd yolov5_new
$ python detect.py  # verify detection

# CODE TO REPRODUCE YOUR ISSUE HERE
```

- **Your custom data.** If your issue is not reproducible in one of our 3 common datasets ([COCO](https://github.com/ultralytics/yolov5/blob/master/data/coco.yaml), [COCO128](https://github.com/ultralytics/yolov5/blob/master/data/coco128.yaml), or [VOC](https://github.com/ultralytics/yolov5/blob/master/data/voc.yaml)) we can not debug it. Visit our [Custom Training Tutorial](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) for guidelines on training your custom data. Examine `train_batch0.jpg` and `test_batch0.jpg` for a sanity check of your labels and images.

- **Your environment.** If your issue is not reproducible in one of the verified environments below we can not debug it. If you are running YOLOv5 locally, verify your environment meets all of the [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies specified below. If in doubt, download Python 3.8.0 from https://www.python.org/, create a new [venv](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/), and install requirements.

If none of these apply to you, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) of your issue. Thank you!


## Requirements

Python 3.8 or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including `torch>=1.7`. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by Xiaocong6** [comment] 2021-04-17 09:09
hi~
Due to machine limitations, I used torch1.4. I have used this code for many days before. And there has been no problem. But yesterday this problem suddenly appeared. I printed the log of nccl. Can you give some suggestions? Help……


ip……:31394:31394 [0] NCCL INFO Bootstrap : Using [0]eth1:ip<0>
ip……:31394:31394 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
ip……:31394:31394 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
ip……:31394:31394 [0] NCCL INFO NET/Socket : Using [0]eth1:ip<0>
NCCL version 2.4.8+cuda10.1
ip……:31395:31395 [1] NCCL INFO Bootstrap : Using [0]eth1:ip<0>
ip……:31395:31395 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
ip……:31395:31395 [1] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
ip……:31395:31395 [1] NCCL INFO NET/Socket : Using [0]eth1:ip<0>
ip……:31394:31665 [0] NCCL INFO Setting affinity for GPU 0 to ff00ff
ip……:31395:31696 [1] NCCL INFO Setting affinity for GPU 1 to ff00ff
ip……:31395:31696 [1] NCCL INFO NCCL_P2P_DISABLE set by environment to 1.
ip……:31394:31665 [0] NCCL INFO NCCL_P2P_DISABLE set by environment to 1.
ip……:31394:31665 [0] NCCL INFO Channel 00 :    0   1
ip……:31395:31696 [1] NCCL INFO Ring 00 : 1[1] -> 0[0] via direct shared memory
ip……:31394:31665 [0] NCCL INFO Ring 00 : 0[0] -> 1[1] via direct shared memory
ip……:31394:31665 [0] NCCL INFO Using 256 threads, Min Comp Cap 7, Trees disabled
ip……:31395:31696 [1] NCCL INFO comm 0x7f87f0001d40 rank 1 nranks 2 cudaDev 1 nvmlDev 1 - Init COMPLETE
ip……:31395:31395 [1] NCCL INFO AllReduce: opCount 0 sendbuff 0x7f87f6000000 recvbuff 0x7f87f6000000 count 1 datatype 1 op 0 root 0 comm 0x7f87f0001d40 [nranks=2] stream 0x555bac0b9ed0
ip……:31394:31665 [0] NCCL INFO comm 0x7fb4ac001d40 rank 0 nranks 2 cudaDev 0 nvmlDev 0 - Init COMPLETE
ip……:31394:31394 [0] NCCL INFO AllReduce: opCount 0 sendbuff 0x7fb4ba000000 recvbuff 0x7fb4ba000000 count 1 datatype 1 op 0 root 0 comm 0x7fb4ac001d40 [nranks=2] stream 0x55acfb31a020
ip……:31394:31394 [0] NCCL INFO Launch mode Parallel
Overriding model.yaml nc=80 with nc=96

                 from  n    params  module                                  arguments                     
  0                -1  1      5280  models.common.Focus                     [3, 48, 3]                    
  1                -1  1     41664  models.common.Conv                      [48, 96, 3, 2]                
  2                -1  1     65280  models.common.C3                        [96, 96, 2]                   
  3                -1  1    166272  models.common.Conv                      [96, 192, 3, 2]               
  4                -1  1    629760  models.common.C3                        [192, 192, 6]                 
  5                -1  1    664320  models.common.Conv                      [192, 384, 3, 2]              
  6                -1  1   2512896  models.common.C3                        [384, 384, 6]                 
  7                -1  1   2655744  models.common.Conv                      [384, 768, 3, 2]              
  8                -1  1   1476864  models.common.SPP                       [768, 768, [5, 9, 13]]        
  9                -1  1   4134912  models.common.C3                        [768, 768, 2, False]          
 10                -1  1    295680  models.common.Conv                      [768, 384, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1   1182720  models.common.C3                        [768, 384, 2, False]          
 14                -1  1     74112  models.common.Conv                      [384, 192, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1    296448  models.common.C3                        [384, 192, 2, False]          
 18                -1  1    332160  models.common.Conv                      [192, 192, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1   1035264  models.common.C3                        [384, 384, 2, False]          
 21                -1  1   1327872  models.common.Conv                      [384, 384, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1   4134912  models.common.C3                        [768, 768, 2, False]          
 24      [17, 20, 23]  1    408141  models.yolo.Detect                      [96, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [192, 384, 768]]
Model Summary: 391 layers, 21440301 parameters, 21440301 gradients

ip……:31395:31395 [1] NCCL INFO Broadcast: opCount 1 sendbuff 0x7f87e4000000 recvbuff 0x7f87e4000000 count 21477873 datatype 7 op 0 root 0 comm 0x7f87f0001d40 [nranks=2] stream 0x555bac0b9ed0
ip……:31395:31395 [1] NCCL INFO Broadcast: opCount 2 sendbuff 0x7f87ed5fba00 recvbuff 0x7f87ed5fba00 count 83 datatype 4 op 0 root 0 comm 0x7f87f0001d40 [nranks=2] stream 0x555bac0b9ed0
Scaled weight_decay = 0.0005
Optimizer groups: 86 .bias, 86 conv.weight, 83 other
ip……:31395:31395 [1] NCCL INFO AllReduce: opCount 3 sendbuff 0x7f87ed5fbe00 recvbuff 0x7f87ed5fbe00 count 1 datatype 1 op 0 root 0 comm 0x7f87f0001d40 [nranks=2] stream 0x555bac0b9ed0
ip……:31394:31394 [0] NCCL INFO Broadcast: opCount 1 sendbuff 0x7fb49a000000 recvbuff 0x7fb49a000000 count 21477873 datatype 7 op 0 root 0 comm 0x7fb4ac001d40 [nranks=2] stream 0x55acfb31a020
ip……:31394:31394 [0] NCCL INFO Broadcast: opCount 2 sendbuff 0x7fb4a35f2c00 recvbuff 0x7fb4a35f2c00 count 83 datatype 4 op 0 root 0 comm 0x7fb4ac001d40 [nranks=2] stream 0x55acfb31a020

[34m[1mtrain: [0mScanning '/val.cache' for images and labels... 5995 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5995/5995 [00:00<?, ?it/s]
[34m[1mtrain: [0mScanning '/val.cache' for images and labels... 5995 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5995/5995 [00:00<00:00, 69079265.05it/s]
ip……:31394:31394 [0] NCCL INFO AllReduce: opCount 3 sendbuff 0x7fb4a35f2c00 recvbuff 0x7fb4a35f2c00 count 1 datatype 1 op 0 root 0 comm 0x7fb4ac001d40 [nranks=2] stream 0x55acfb31a020
nw= 0

[34m[1mval: [0mScanning '/val.cache' for images and labels... 5995 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5995/5995 [00:00<?, ?it/s]
[34m[1mval: [0mScanning '/val.cache' for images and labels... 5995 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5995/5995 [00:00<00:00, 58205677.04it/s]
nw= 0
Plotting labels... 

[34m[1mtrain: [0mScanning '/val.cache' for images and labels... 5995 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5995/5995 [00:00<?, ?it/s]
[34m[1mtrain: [0mScanning '/val.cache' for images and labels... 5995 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5995/5995 [00:00<00:00, 69269566.06it/s]
nw= 0
ip……:31395:31395 [1] NCCL INFO Broadcast: opCount 4 sendbuff 0x7f87eb591a00 recvbuff 0x7f87eb591a00 count 37572 datatype 7 op 0 root 0 comm 0x7f87f0001d40 [nranks=2] stream 0x555bac0b9ed0
ip……:31395:31395 [1] NCCL INFO Broadcast: opCount 5 sendbuff 0x7f87ed5fc400 recvbuff 0x7f87ed5fc400 count 83 datatype 4 op 0 root 0 comm 0x7f87f0001d40 [nranks=2] stream 0x555bac0b9ed0

[34m[1mautoanchor: [0mAnalyzing anchors... anchors/target = 5.48, Best Possible Recall (BPR) = 1.0000
Image sizes 640 train, 640 test
Using 0 dataloader workers
Logging results to runs/train/exp51
Starting training for 60 epochs...

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size

  0%|          | 0/750 [00:00<?, ?it/s]ip……:31394:31394 [0] NCCL INFO Broadcast: opCount 4 sendbuff 0x7fb497bb0000 recvbuff 0x7fb497bb0000 count 37572 datatype 7 op 0 root 0 comm 0x7fb4ac001d40 [nranks=2] stream 0x55acfb31a020
ip……:31394:31394 [0] NCCL INFO Broadcast: opCount 5 sendbuff 0x7fb4ab5fa000 recvbuff 0x7fb4ab5fa000 count 83 datatype 4 op 0 root 0 comm 0x7fb4ac001d40 [nranks=2] stream 0x55acfb31a020
ip……:31395:31831 [1] NCCL INFO AllReduce: opCount 6 sendbuff 0x7f87eb170000 recvbuff 0x7f87eb170000 count 408909 datatype 7 op 0 root 0 comm 0x7f87f0001d40 [nranks=2] stream 0x555bac0b9ed0

      0/59    0.753G    0.1248   0.04918    0.1147    0.2887        29       640:   0%|          | 0/750 [00:06<?, ?it/s]
      0/59    0.753G    0.1248   0.04918    0.1147    0.2887        29       640:   0%|          | 1/750 [00:07<1:32:31,  7.41s/it]ip……:31394:31394 [0] NCCL INFO Broadcast: opCount 6 sendbuff 0x7fb41faf3000 recvbuff 0x7fb41faf3000 count 37572 datatype 7 op 0 root 0 comm 0x7fb4ac001d40 [nranks=2] stream 0x55acfb31a020
ip……:31394:31394 [0] NCCL INFO Broadcast: opCount 7 sendbuff 0x7fb495fffc00 recvbuff 0x7fb495fffc00 count 83 datatype 4 op 0 root 0 comm 0x7fb4ac001d40 [nranks=2] stream 0x55acfb31a020

      0/59     1.74G    0.1247   0.04888    0.1125     0.286        28       640:   0%|          | 1/750 [00:08<1:32:31,  7.41s/it]
      0/59     1.74G    0.1247   0.04888    0.1125     0.286        28       640:   0%|          | 2/750 [00:08<1:09:40,  5.59s/it]ip……:31394:31394 [0] NCCL INFO Broadcast: opCount 8 sendbuff 0x7fb4397d4400 recvbuff 0x7fb4397d4400 count 37572 datatype 7 op 0 root 0 comm 0x7fb4ac001d40 [nranks=2] stream 0x55acfb31a020
ip……:31394:31394 [0] NCCL INFO Broadcast: opCount 9 sendbuff 0x7fb4194ec400 recvbuff 0x7fb4194ec400 count 83 datatype 4 op 0 root 0 comm 0x7fb4ac001d40 [nranks=2] stream 0x55acfb31a020

      0/59     1.75G    0.1243   0.05343    0.1117    0.2894        43       640:   0%|          | 2/750 [00:09<1:09:40,  5.59s/it]
      0/59     1.75G    0.1243   0.05343    0.1117    0.2894        43       640:   0%|          | 3/750 [00:09<53:22,  4.29s/it]  ip……:31394:31394 [0] NCCL INFO Broadcast: opCount a sendbuff 0x7fb4195d9400 recvbuff 0x7fb4195d9400 count 37572 datatype 7 op 0 root 0 comm 0x7fb4ac001d40 [nranks=2] stream 0x55acfb31a020
ip……:31394:31394 [0] NCCL INFO Broadcast: opCount b sendbuff 0x7fb4069f8600 recvbuff 0x7fb4069f8600 count 83 datatype 4 op 0 root 0 comm 0x7fb4ac001d40 [nranks=2] stream 0x55acfb31a020

      0/59     1.75G     0.124   0.05496    0.1105    0.2895        38       640:   0%|          | 3/750 [00:10<53:22,  4.29s/it]
      0/59     1.75G     0.124   0.05496    0.1105    0.2895        38       640:   1%|          | 4/750 [00:10<40:39,  3.27s/it]ip……:31394:31394 [0] NCCL INFO Broadcast: opCount c sendbuff 0x7fb4195b5a00 recvbuff 0x7fb4195b5a00 count 37572 datatype 7 op 0 root 0 comm 0x7fb4ac001d40 [nranks=2] stream 0x55acfb31a020
ip……:31394:31394 [0] NCCL INFO Broadcast: opCount d sendbuff 0x7fb4a94b5e00 recvbuff 0x7fb4a94b5e00 count 83 datatype 4 op 0 root 0 comm 0x7fb4ac001d40 [nranks=2] stream 0x55acfb31a020

      0/59     1.77G    0.1246   0.05399    0.1108    0.2895        32       640:   1%|          | 4/750 [00:11<40:39,  3.27s/it]
      0/59     1.77G    0.1246   0.05399    0.1108    0.2895        32       640:   1%|          | 5/750 [00:11<30:35,  2.46s/it]ip……:31394:31394 [0] NCCL INFO Broadcast: opCount e sendbuff 0x7fb4267c6800 recvbuff 0x7fb4267c6800 count 37572 datatype 7 op 0 root 0 comm 0x7fb4ac001d40 [nranks=2] stream 0x55acfb31a020
ip……:31394:31394 [0] NCCL INFO Broadcast: opCount f sendbuff 0x7fb4067fd000 recvbuff 0x7fb4067fd000 count 83 datatype 4 op 0 root 0 comm 0x7fb4ac001d40 [nranks=2] stream 0x55acfb31a020

      0/59     1.77G    0.1241   0.05489    0.1106    0.2896        37       640:   1%|          | 5/750 [00:12<30:35,  2.46s/it]
      0/59     1.77G    0.1241   0.05489    0.1106    0.2896        37       640:   1%|          | 6/750 [00:12<23:37,  1.90s/it]ip……:31394:31394 [0] NCCL INFO Broadcast: opCount 10 sendbuff 0x7fb406fd4000 recvbuff 0x7fb406fd4000 count 37572 datatype 7 op 0 root 0 comm 0x7fb4ac001d40 [nranks=2] stream 0x55acfb31a020
ip……:31394:31394 [0] NCCL INFO Broadcast: opCount 11 sendbuff 0x7fb4069fd600 recvbuff 0x7fb4069fd600 count 83 datatype 4 op 0 root 0 comm 0x7fb4ac001d40 [nranks=2] stream 0x55acfb31a020

      0/59     1.77G    0.1246   0.05465    0.1116    0.2909        39       640:   1%|          | 6/750 [00:12<23:37,  1.90s/it]
      0/59     1.77G    0.1246   0.05465    0.1116    0.2909        39       640:   1%|          | 7/750 [00:12<18:08,  1.46s/it]ip……:31394:31394 [0] NCCL INFO Broadcast: opCount 12 sendbuff 0x7fb4079cf800 recvbuff 0x7fb4079cf800 count 37572 datatype 7 op 0 root 0 comm 0x7fb4ac001d40 [nranks=2] stream 0x55acfb31a020
ip……:31394:31394 [0] NCCL INFO Broadcast: opCount 13 sendbuff 0x7fb4069fd200 recvbuff 0x7fb4069fd200 count 83 datatype 4 op 0 root 0 comm 0x7fb4ac001d40 [nranks=2] stream 0x55acfb31a020

      0/59     1.77G    0.1241   0.05436    0.1113    0.2897        29       640:   1%|          | 7/750 [00:12<18:08,  1.46s/it]
      0/59     1.77G    0.1241   0.05436    0.1113    0.2897        29       640:   1%|          | 8/750 [00:12<14:15,  1.15s/it]ip……:31394:31394 [0] NCCL INFO Broadcast: opCount 14 sendbuff 0x7fb41e7c6800 recvbuff 0x7fb41e7c6800 count 37572 datatype 7 op 0 root 0 comm 0x7fb4ac001d40 [nranks=2] stream 0x55acfb31a020
ip……:31394:31394 [0] NCCL INFO Broadcast: opCount 15 sendbuff 0x7fb4067ff800 recvbuff 0x7fb4067ff800 count 83 datatype 4 op 0 root 0 comm 0x7fb4ac001d40 [nranks=2] stream 0x55acfb31a020
ip……:31395:31831 [1] NCCL INFO AllReduce: opCount 7 sendbuff 0x7f87e2000000 recvbuff 0x7f87e2000000 count 7200384 datatype 7 op 0 root 0 comm 0x7f87f0001d40 [nranks=2] stream 0x555bac0b9ed0

      0/59     1.77G    0.1232   0.05538    0.1111    0.2897        35       640:   1%|          | 8/750 [00:13<14:15,  1.15s/it]
      0/59     1.77G    0.1232   0.05538    0.1111    0.2897        35       640:   1%|          | 9/750 [00:13<11:37,  1.06it/s]ip……:31394:31394 [0] NCCL INFO Broadcast: opCount 16 sendbuff 0x7fb4067dac00 recvbuff 0x7fb4067dac00 count 37572 datatype 7 op 0 root 0 comm 0x7fb4ac001d40 [nranks=2] stream 0x55acfb31a020
ip……:31394:31394 [0] NCCL INFO Broadcast: opCount 17 sendbuff 0x7fb4067ff800 recvbuff 0x7fb4067ff800 count 83 datatype 4 op 0 root 0 comm 0x7fb4ac001d40 [nranks=2] stream 0x55acfb31a020

ip……:31395:31579 [0] init.cc:1247 NCCL WARN Mismatched collective detected, please check your collective calls at and around rank 1. You can use NCCL_DEBUG=INFO and NCCL_DEBUG_SUBSYS=COLL to see the collective logs

**Comment by Xiaocong6** [comment] 2021-04-17 09:15
I tried some methods provided on the Internet, such as setting pin_memory, workers set to 0, and setting cv2.setNumThreads(0), but none of them worked.

**Closed as completed** 2021-04-22 00:19 UTC
Labels: question

**Comment by huynhcuong98** [comment] 2021-05-24 08:14
Same problem. It has no change without any reporting error when I use multi gpu. 
![image](https://user-images.githubusercontent.com/38148534/119317625-7fd01800-bca2-11eb-9944-9edbabc449cc.png)

**Comment by glenn-jocher** [comment] 2021-05-24 09:53
@huynhcuong98 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide code that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* **Minimal** – Use as little code as possible that still produces the same problem
* **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for Ultralytics to attempt to reproduce your problem, the code that produces the problem must be:

* **Current** – Verify that your code is up-to-date with current GitHub master, and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. Ultralytics does not provide support for customized code.

If you believe your problem meets all of the above criteria, we suggest you close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!
