### ISSUE TITLE
Not able to open video detection results on browser.

### ISSUE THREAD

**Issue by macpreet** [ultralytics/yolov5#7738] opened 2022-05-09 09:04 UTC
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm using the object detection model  on saved videos and saving the results in a local folder.  The videos are streaming fine in the Media players with the bounding boxes and labels but only a black screen appears when trying to open on any browser.  Everything is working well in case of images.
Any Help Please!

**Comment by glenn-jocher** [comment] 2022-05-09 09:25
@macpreet 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by macpreet** [comment] 2022-05-09 09:49
@glenn-jocher  I just wanted to ask that why saved video detection results with labels are not opening in the browser. Is this a video format issue ?

**Closed as completed** 2022-05-17 10:32 UTC
Labels: question

**Comment by glenn-jocher** [comment] 2023-11-15 09:37
Hi @macpreet 👋, great to hear from you! There could be a few factors causing this issue, such as the video format, browser compatibility, or specific settings in the detection results. We recommend trying different video formats and checking the compatibility with various browsers to pinpoint the root cause. Also, ensure that the video results are being saved in a manner supported by common web video players. If the issue persists, feel free to provide a minimum reproducible example so we can investigate further. Thank you! 😃
