### ISSUE TITLE
got error all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 114824 has 1 dimension(s)

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#1507] opened 2020-11-25 10:48 UTC
hello, last month i clone this repo, and can train successfully, but i reclone this repository, then run :
`nohup python3 train.py --data data/data.yaml --cfg models/yolov5s.yaml --weights '' --img 640 --batch-size 64 &`

got error : 
```
Traceback (most recent call last):
  File "train.py", line 491, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 186, in train
    mlc = np.concatenate(dataset.labels, 0)[:, 0].max()  # max label class
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 114824 has 1 dimension(s)
```

why i got this ? any suggest ? thank you

**Comment by glenn-jocher** [comment] 2020-11-25 11:11
Hello, thank you for your interest in YOLOv5! This issue seems to lack the minimum requirements for a proper response, or is insufficiently detailed for us to help you. Please note that most technical problems are due to:

- **Your modified or out-of-date code**. If your issue is not reproducible in a new `git clone` version of this repo we can not debug it. Before going further run this code and verify your issue persists:
```bash
$ git clone https://github.com/ultralytics/yolov5 yolov5_new  # clone latest
$ cd yolov5_new
$ python detect.py  # verify detection

# CODE TO REPRODUCE YOUR ISSUE HERE
```

- **Your custom data.** If your issue is not reproducible in one of our 3 common datasets ([COCO](https://github.com/ultralytics/yolov5/blob/master/data/coco.yaml), [COCO128](https://github.com/ultralytics/yolov5/blob/master/data/coco128.yaml), or [VOC](https://github.com/ultralytics/yolov5/blob/master/data/voc.yaml)) we can not debug it. Visit our [Custom Training Tutorial](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) for guidelines on training your custom data. Examine `train_batch0.jpg` and `test_batch0.jpg` for a sanity check of your labels and images.

- **Your environment.** If your issue is not reproducible in one of the verified environments below we can not debug it. If you are running YOLOv5 locally, verify your environment meets all of the [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies specified below. If in doubt, download Python 3.8.0 from https://www.python.org/, create a new [venv](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/), and then install requirements.

If none of these apply to you, we suggest you close this issue and raise a new one using the **Bug Report template**, providing screenshots and **minimum viable code to reproduce your issue**. Thank you!


## Requirements

Python 3.8 or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including `torch>=1.6`. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by cesarandreslopez** [comment] 2020-11-25 18:59
Same error seen here.

**Comment by cesarandreslopez** [comment] 2020-11-25 19:13
Error does not show with the same command on the v3.1 release.

**Comment by glenn-jocher** [comment] 2020-11-25 19:32
@cesarandreslopez @blinkbink thanks for spotting this! This should be resolved in PR https://github.com/ultralytics/yolov5/pull/1513. Please git pull and try again.

**Closed as completed** 2020-11-25 19:33 UTC
Labels: bug

**Comment by eldarkurtic** [comment] 2020-11-25 22:14
I have tried it now and the same issue exists except the index has changed from 114824 to 42. The error looks like this:
```
Optimizer groups: 76 .bias, 76 conv.weight, 73 other
Scanning '../coco/labels/train2017.cache' for images and labels... 117266 found, 1021 missing, 0 empty, 0 corrupted: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 118286/118286 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 520, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 191, in train
    mlc = np.concatenate(dataset.labels, 0)[:, 0].max()  # max label class
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 42 has 1 dimension(s)
```
Interesting thing is that the code runs without this issue when I run it with `coco128.yaml`.

**Comment by glenn-jocher** [comment] 2020-11-25 22:42
@eldarkurtic if you were getting this error before, then you may have a corrupted cache that is not being replaced. Please delete any *.cache files in your datasets and try again.

**Comment by eldarkurtic** [comment] 2020-11-25 22:58
Completely forgot about the cache, this solves the issue. Thanks.

**Comment by glenn-jocher** [comment] 2020-11-25 23:14
@eldarkurtic normally the cache is automatically deleted and rewritten if needed (i.e. if the dataset changes), but this special case (the #1513 bug) would require the cache to be manually deleted unfortunately. Maybe I should have baked in some more checks into the code... but anyway yes if anyone still has problems deleting the *.cache file in your dataset should clear the problem.
