### ISSUE TITLE
error on test.py

### ISSUE THREAD

**Issue by jerrywgz** [ultralytics/yolov5#10] opened 2020-06-02 07:52 UTC
I try to test yolov5l on v100 using followed commend
``` python
python test.py --img-size 640 --conf-thres 0.1 --batch-size 16 --weights weights/yolov5l.pt --data data/coco.yaml --device 0
```
RuntimeError is reported, but it works on detect.py and train.py
![image](https://user-images.githubusercontent.com/22989727/83494744-4e869700-a4e9-11ea-83df-968a6b667c93.png)

I used the docker image (ultralytics/yolov5:latest) you provided.

**Comment by glenn-jocher** [comment] 2020-06-02 17:21
@jerrywgz thank you for the bug report! This looks familiar, I believe it's caused by a thop dependency used for calculating FLOPs. You can `pip uninstall thop` to fix this in your container.

We've pushed a fixed image to dockerhub as well, so you if you pull you should receive the fix now.

**Closed as completed** 2020-06-05 21:53 UTC
Labels: bug
