### ISSUE TITLE
Error : Input type (torch.FloatTensor) and weight type (torch.HalfTensor) should be the same 

### ISSUE THREAD

**Issue by niharpatel1999** [ultralytics/yolov5#101] opened 2020-06-16 17:22 UTC
I trained my yolov5l model on Colab and updated the last.pt file to run inference on the local machine. But it shows the following error 
**RuntimeError: Input type (torch.FloatTensor) and weight type (torch.HalfTensor) should be the same**
while executing 
`python detect.py --weights weights/last.pt --img 416 --conf 0.4 --source ../test --device cpu`

**Comment by glenn-jocher** [comment] 2020-06-16 17:25
@niharpatel1999 ok thanks for the bug report. I will try to reproduce.

**Comment by glenn-jocher** [comment] 2020-06-16 17:27
I used our colab notebook to train a model for 3 epochs, then used last.pt to run inference. No problem at all, everything works fine.

<img width="1509" alt="Screen Shot 2020-06-16 at 10 26 41 AM" src="https://user-images.githubusercontent.com/26833433/84807300-e2f9fa80-afbb-11ea-8601-c6c5bd5a7ea8.png">

**Comment by niharpatel1999** [comment] 2020-06-16 17:35
There is no issue if we run inference on colab .
But try downloading the last.pt file trained on GPU accelerated colab and
run inference on desktop than it would show error.

**Comment by glenn-jocher** [comment] 2020-06-16 17:37
@niharpatel1999 ah, ok I see. I will try to reproduce your use case here.

**Comment by glenn-jocher** [comment] 2020-06-16 17:43
@niharpatel1999 I repeated your steps, everything works fine for me. I don't see any problems. You may want to repeat your steps with the latest version of the repo, perhaps your bug has already been resolved.

You can also run models on cpu in colab like this by the way:
`python detect.py --device cpu`

**Comment by niharpatel1999** [comment] 2020-06-16 17:54
Thanks.

**Comment by deeppatel4557** [comment] 2020-06-18 03:30
@glenn-jocher, I am @niharpatel1999 teammate the weights tensor in our case is of the type torch.HalfTensor because we have trained it on GPU so there is an error of Input type torch.FloatTensor and weight type of torch.HalfTensor should be the same. we resolved that error just by changing one line of code in detect.py. Line number 23 has model.to(device).eval() to model.to(device).float().eval() by doing this we resolved the error by changing the type of weight tensor to float.It executed successfully on the CPU.Thanks for your support.

**Comment by glenn-jocher** [comment] 2020-06-18 03:33
This should have been resolved in recent commits. Please git pull and try again.

**Closed as completed** 2020-06-20 06:07 UTC
Labels: bug

**Comment by rubysiu** [comment] 2022-03-04 00:43
@deeppatel4557 Thank you very much. Your proposal is very helpful to me
