### ISSUE TITLE
KeyError: "./weights/yolov5s.pt is not compatible with ./models/yolov5s.yaml. Specify --weights '' or specify a --cfg compatible with ./weights/yolov5s.pt."

### ISSUE THREAD

**Issue by NacirB** [ultralytics/yolov5#222] opened 2020-06-28 15:10 UTC
I'm training yolov5x to predict **one class**.
I created a custom **yolo5x.yaml** where **nc == 1.** And I want to train my model using pretrained coco weights. 

And When I load coco pretrained weights like this : **--weight yolov5x.pt**, I receive an error saying :  yolov5x.pt is not compatible with yolov5x.yaml.
How can I load pretrained weights  ? and how to fix this issue ?

**Comment by glenn-jocher** [comment] 2020-06-28 23:00
@NacirB thanks for the bug report. Do you see this error with other models as well or only v5x?

**Comment by wuyunxiangwyx** [comment] 2020-06-29 06:54
I encounter this error with model yolov5s.pt when I'm load yolov5s.pt to train with only  one class.

**Comment by wuyunxiangwyx** [comment] 2020-06-29 07:38
![image](https://user-images.githubusercontent.com/39322157/85986300-9502df00-ba1e-11ea-9e3f-88e32d090f65.png)

**Comment by wuyunxiangwyx** [comment] 2020-06-29 07:39
Traceback (most recent call last):
  File "train.py", line 117, in train
    ckpt['model'] = {k: v for k, v in ckpt['model'].float().state_dict().items()
  File "train.py", line 118, in <dictcomp>
    if model.state_dict()[k].shape == v.shape}  # to FP32, filter
KeyError: 'model.2.cv2.conv.weight'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 383, in <module>
    train(hyp)
  File "train.py", line 123, in train
    raise KeyError(s) from e
KeyError: "./weights/yolov5s.pt is not compatible with ./models/yolov5s.yaml. Specify --weights '' or specify a --cfg compatible with ./weights/yolov5s.pt."

**Comment by batrlatom** [comment] 2020-06-29 07:47
Is it the same problem as here? https://github.com/ultralytics/yolov5/issues/203

**Comment by batrlatom** [comment] 2020-06-29 07:49
@glenn-jocher I think it would be extremely helpful to enable transfer learning with any nc

**Comment by wuyunxiangwyx** [comment] 2020-06-29 08:01
it works when i add code 'k in model.state_dict()'  in  train.py  about  line 118.
ckpt['model'] = {k: v for k, v in ckpt['model'].float().state_dict().items()
                             if k in model.state_dict() and model.state_dict()[k].shape == v.shape}

**Comment by glenn-jocher** [comment] 2020-06-29 16:42
@batrlatom @wuyunxiangwyx you should be able to load pretrained weights into a model.yaml configured for any class count. If this is not working there may be a bug, I'll check it out.

**Comment by glenn-jocher** [comment] 2020-06-29 16:53
@batrlatom @wuyunxiangwyx I tested the code with yolov5s on a 1 class dataset and on a 4 class dataset, and everything works correctly. Ah, I think I know what the problem is: 

Model *.pt and *.yaml files are updated frequently in this repo, so if your repo downloaded an older model and you are trying to train with a recent version of the repo, it's possible your new *.yaml is incompatible with the older *.pt file you have. 

To fix this, **delete all official pretrained models from your repo and try your command again**. The newest version of the models will always be downloaded and the problem should be fixed.

**Comment by NacirB** [comment] 2020-06-29 17:33
It works when we download the new files. 
Thanks.

**Comment by glenn-jocher** [comment] 2020-06-29 18:47
@NacirB ok got it. I may need to add some logic to detect out of date model.pt files, but this is quite complicated, as each model would require an internal version number which would need to be compared to a global deprecation list probably. I think I will simply update the error message to recommend that all current models be deleted.

**Comment by NacirB** [comment] 2020-06-29 19:19
@glenn-jocher  Yeah I think that an error message is enough to inform people about changes.

**Comment by AshutoshAJ** [comment] 2020-06-29 19:23
Hey @NacirB can you help with me this?? Too much urgent. Thanks in advance.
https://github.com/ultralytics/yolov5/issues/221

**Comment by glenn-jocher** [comment] 2020-06-29 19:45
All done! Hope this helps in the future.

**Closed as completed by glenn-jocher** 2020-06-29 19:45 UTC
Labels: bug

**Comment by NacirB** [comment] 2020-06-30 00:24
@AshutoshAJ  you only need to donwload the right yolov5x.yaml file which you can find it [here](https://drive.google.com/file/d/1v0EQsEvH52tTI0oQNGnGIj4zUv9U1_ir/view)

**Comment by hktxt** [comment] 2020-07-06 14:34
trust me, if you copy your code to another machine, you will get same error.
however, it runs normally on the original machine. That's werid!
change nothing, just different machine. one runs ok, one not.

**Comment by glenn-jocher** [comment] 2020-07-06 17:22
@hktxt you should delete any incompatible weights as they may be out of date, it will download the latest only if it does not find any on your system.

**Comment by sumanttyagi** [comment] 2020-07-28 19:47
just ran the code today , using all the latest file .Still facing the same issue also the class has been modified to nc : 1, ? Please suggest the fix

**Comment by glenn-jocher** [comment] 2020-07-28 19:49
@sumanttyagi training currently operates correctly. Suggest you use the latest code in a reproducible environment, and also delete any old weights you may have.

## Environment

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

**Comment by sumanttyagi** [comment] 2020-07-28 20:01
> @sumanttyagi training currently operates correctly. Suggest you use the latest code in a reproducible environment, and also delete any old weights you may have.
> 
> ## Environment
> YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):
> 
> * **Google Colab Notebook** with free GPU: [![Open In Colab](https://camo.githubusercontent.com/52feade06f2fecbf006889a904d221e6a730c194/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb)
> * **Kaggle Notebook** with free GPU: https://www.kaggle.com/models/ultralytics/yolov5
> * **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
> * **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://camo.githubusercontent.com/caa63570e9f4e9771b02fc86d87e78aad3bf9785/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f796f6c6f76353f6c6f676f3d646f636b6572)

I have used both the weights for model name yolo5s.yaml & yolo5x.yaml both is giving similar error eyError: "yolov5/weights/yolov5s.pt is not compatible with yolov5/models/yolov5s.yaml. This may be due to model differences or yolov5/weights/yolov5s.pt may be out of date. Please delete or update yolov5/weights/yolov5s.pt and try again, or use --weights '' to train from scratch."
CPU times: user 38.2 ms, sys: 10.3 ms, total: 48.5 ms
Wall time: 10.2 s
 , files i am able to run from scratch but not with coco weight ? 

> @sumanttyagi training currently operates correctly. Suggest you use the latest code in a reproducible environment, and also delete any old weights you may have.
> 
> ## Environment
> YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):
> 
> * **Google Colab Notebook** with free GPU: [![Open In Colab](https://camo.githubusercontent.com/52feade06f2fecbf006889a904d221e6a730c194/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb)
> * **Kaggle Notebook** with free GPU: https://www.kaggle.com/models/ultralytics/yolov5
> * **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
> * **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://camo.githubusercontent.com/caa63570e9f4e9771b02fc86d87e78aad3bf9785/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f796f6c6f76353f6c6f676f3d646f636b6572)

Just checked the information provide by you it is working ........Happy Learning

**Comment by pderrenger** [comment] 2024-10-20 23:59
Great to hear it's working now! If you have any more questions, feel free to ask.

**Comment by pderrenger** [comment] 2024-10-26 18:47
Great to hear it's working now! If you have any more questions, feel free to ask.
