### ISSUE TITLE
'silent_list' object has no attribute 'patches'

### ISSUE THREAD

**Issue by jhlee508** [ultralytics/yolov5#3195] opened 2021-05-17 11:51 UTC
## ❔Question
I was just training custom datasets and this error occurred.
What is the reason of this error? Could you help me?

## Error Message
Traceback (most recent call last):
  File "train.py", line 542, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 210, in train
    plot_labels(labels, names, save_dir, loggers)
  File "/content/yolov5/utils/plots.py", line 303, in plot_labels
    [y[2].patches[i].set_color([x / 255 for x in colors(i)]) for i in range(nc)]  # update colors
  File "/content/yolov5/utils/plots.py", line 303, in <listcomp>
    [y[2].patches[i].set_color([x / 255 for x in colors(i)]) for i in range(nc)]  # update colors
AttributeError: 'silent_list' object has no attribute 'patches'

**Comment by glenn-jocher** [comment] 2021-05-17 11:57
@jhlee508 this seems to be associated with the recent PR https://github.com/ultralytics/yolov5/pull/3192.

I don't recognize the error message though. If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose), providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!

**Comment by testproducts20** [comment] 2021-05-17 15:18
same error when training with yolov5s custom datasets on google colab
with the following param
!python train.py --img 416 --batch 16 --epochs 237 --data ../data.yaml --weights **yolov5s**.pt --nosave --cache

**Comment by glenn-jocher** [comment] 2021-05-17 15:48
@jhlee508 @testproducts20 good news 😃! Your original issue may now been fixed ✅ in PR #3214.  To receive this update you can:
- `git pull` from within your `yolov5/` directory
- `git clone https://github.com/ultralytics/yolov5` again
- Force-reload [PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/): `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- View our updated notebooks:  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Closed as completed** 2021-05-17 15:47 UTC
Labels: question
