### ISSUE TITLE
Non UTF-8 filenames caching bug

### ISSUE THREAD

**Issue by nebiyebulan** [ultralytics/yolov5#5654] opened 2021-11-15 13:16 UTC
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hello, I downloaded the yolov5 folder to my desktop. I imported my own dataset. I created a virtual environment and downloaded the necessary libraries. I want to continue my education with GPU without interruption. so i am using jetson xavier agx developer kit. after starting the tutorial i am getting this error and i could not solve it please help.
@timstokman @cgerum @farleylai @adrianholovaty @topiaruss 
![Ekran Görüntüsü - 2021-11-15 16-06-58](https://user-images.githubusercontent.com/62153842/141788028-775d2d84-9e35-4102-9c5e-644fad6691b3.png)
![Ekran Görüntüsü - 2021-11-15 16-15-40](https://user-images.githubusercontent.com/62153842/141788211-f4c91f72-2801-4588-80e0-0594af9d3ddd.png)

**Comment by glenn-jocher** [comment] 2021-11-15 14:06
@nebiyebulan this is interesting, thanks for asking this question (though you should probably do a bug report instead). It seems hashing is crashing on non-UTF-8 characters in some of your filenames. 

Please update your get_hash() function in your [utils/dataset.py](https://github.com/ultralytics/yolov5/blob/master/utils/datasets.py) file, re-run your command and paste your resulting debug string here. Thank you.

```python
def get_hash(paths):
    # Returns a single hash value of a list of paths (files or dirs)
    size = sum(os.path.getsize(p) for p in paths if os.path.exists(p))  # sizes
    h = hashlib.md5(str(size).encode())  # hash sizes

    # DEBUG
    s = ''.join(set(''.join(paths)))
    print('DEBUG STRING: ', s)
    
    h.update(''.join(paths).encode())  # hash paths
    return h.hexdigest()  # return hash
```

**Comment by nebiyebulan** [comment] 2021-11-15 14:17
thanks @glenn-jocher  i updated it but a different error popped up
![a](https://user-images.githubusercontent.com/62153842/141797092-9297e9e1-857d-4acb-a9d4-27bb3091951d.png)

**Comment by glenn-jocher** [comment] 2021-11-15 14:29
@nebiyebulan if the print statement is not working then you can just put a breakpoint in the code at that spot and past the value of `s` here.

**Comment by glenn-jocher** [comment] 2021-11-15 14:32
@nebiyebulan this should produce a string of unique characters in your entire dataset. For COCO 128 for example I see this (after adding sorted):

```python
    # DEBUG
    s = ''.join(sorted(set(''.join(paths))))
    print('DEBUG STRING: ', s)

DEBUG STRING:  ./0123456789abcdegijlmnoprstx
```

You've basically got some really strange characters in your dataset that are breaking python.

**Comment by nebiyebulan** [comment] 2021-11-15 14:44
yes @glenn-jocher this is turkish character in my dataset. but I can do this training on colab. I could not run it here

**Comment by nebiyebulan** [comment] 2021-11-15 14:44
> evet @glenn-jocher bu benim veri setimdeki türk karakteri. ama bu eğitimi colab üzerinde yapabilirim. burada çalıştıramadım

example ç, ş , ö

**Comment by glenn-jocher** [comment] 2021-11-15 14:59
@nebiyebulan it's not those characters. It's a character in s that won't encode.

```python
print('ç, ş , ö'.encode())
b'\xc3\xa7, \xc5\x9f , \xc3\xb6'
```

**Comment by glenn-jocher** [comment] 2021-11-15 15:00
@nebiyebulan also if your training completes successfully in Colab but not locally, then the issue is with your local environment. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

[**Python>=3.6.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
$ git clone https://github.com/ultralytics/yolov5
$ cd yolov5
$ pip install -r requirements.txt
```

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by nebiyebulan** [comment] 2021-11-19 11:05
I did everything you said, now I'm getting this error. @glenn-jocher 
![1](https://user-images.githubusercontent.com/62153842/142612549-89f14dc3-749c-44c7-ab0d-3262891707a0.png)

**Comment by glenn-jocher** [comment] 2021-11-19 12:51
@nebiyebulan 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Closed as completed** 2021-11-19 13:09 UTC
Labels: bug

**Comment by glenn-jocher** [comment] 2021-12-13 17:48
@nebiyebulan removing TODO as you've closed this issue.
