### ISSUE TITLE
Fp16 models return no detections

### ISSUE THREAD

**Issue by fnando1995** [ultralytics/yolov5#6766] opened 2022-02-24 17:21 UTC
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I used the validate and detect files for different models, changing fp32 and fp16 for tensorrt framework. I notice that fp16 models return NO detections (0 detects). Does anyone can point out what could this be? I make many imports ,changing fp, batchsize, model version, image size; but all fp16 models do not return detections, only fp32.

**Comment by glenn-jocher** [comment] 2022-02-24 18:52
@fnando1995 this is a CUDA/conda/windows bug that affects some install configurations. Most of the time this is caused by CUDA 11 incompatibilities and will be resolved by downgrading to CUDA 10, i.e. 10.2.

**Comment by fnando1995** [comment] 2022-02-24 19:15
Hello @glenn-jocher, I tested in this 2 environments

Environment 1:
ubuntu 21.04
cuda 11.4
python3-pip

Environment 2:
Jetson nano jetpack 4.6
cuda 10.2
python3-pip

Any thoughts?

**Comment by DavidBaldsiefen** [comment] 2022-02-25 16:33
Did you run the `detect.py` and `val.py` with the `--half` flag? `export.py` creates engines which need FP16 inputs in order to work.

**Comment by fnando1995** [comment] 2022-02-25 16:53
@DavidBaldsiefen That was the problem!, but I was doing the change directly but, the argsparse default for half was changing it. Thanks.

**Comment by fnando1995** [comment] 2022-02-25 17:00
@DavidBaldsiefen @glenn-jocher 
Where exactly does the half variable change the model for half inference?

**Closed as completed** 2022-02-25 17:06 UTC
Labels: question
