### ISSUE TITLE
Failed to Run WebCam Inference 

### ISSUE THREAD

**Issue by charlieguo0610** [ultralytics/yolov5#8442] opened 2022-07-02 13:59 UTC
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/48096429/177003934-dd0a8ef6-d916-4219-94e3-6add0984ae82.png">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment] 2022-07-02 16:46
@charlieguo0610 duplicate of many existing issues, original at https://github.com/pytorch/pytorch/issues/77886

torch team is aware of issue but feel free to leave your feedback at the issue above.

**Comment by glenn-jocher** [comment] 2022-07-02 16:47
@charlieguo0610 good news 😃! Your original issue may now be fixed ✅ in PR #8446. This PR reverts MPS preference if found as torch 1.12 is still not MPS compatible.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Closed as completed by glenn-jocher** 2022-07-02 16:47 UTC
Labels: bug, duplicate
