### ISSUE TITLE
tensorrt

### ISSUE THREAD

**Issue by 123456789mojtaba** [ultralytics/yolov5#512] opened 2020-07-25 04:59 UTC
Hi.
thanks because of your repo.
Can you pytorch_onnx to tensorrt in your yolov5 github repo?
Ty

**Comment by glenn-jocher** [comment] 2020-07-25 05:27
@123456789mojtaba closing as duplicate of existing issues. Please do some research before raising new issues.

https://github.com/TrojanXu/yolov5-tensorrt
https://github.com/wang-xinyu/tensorrtx

**Closed as completed by glenn-jocher** 2020-07-25 05:27 UTC
Labels: question
