### ISSUE TITLE
Type error when using detect.py

### ISSUE THREAD

**Issue by leemengwei** [ultralytics/yolov5#10412] opened 2022-12-06 06:17 UTC
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

python detect.py --weights '/home/lmw/leemengwei/triton_pack/commons/all_onnx_models/side_pig_fp16.onnx' --source '/home/lmw/leemengwei/videos/1668651935.mp4' --half
report:
Type parameter (T) of Optype (Concat) bound to different types (tensor(float) and tensor(float16) in node (Concat_350)

### Additional

pip list|grep torch
torch                   1.7.0
torch-tb-profiler       0.1.0
torchvision             0.8.2

pip list|grep onnx   yeilds
onnx                    1.11.0
onnx-graphsurgeon       0.3.12
onnx-simplifier         0.3.6
onnxoptimizer           0.2.6
onnxruntime-gpu         1.13.1

yolov5  version: 
commit 7398d2d77cbac9f66259926d49c26bfa3c257a9b (HEAD -> master, origin/master, origin/HEAD)
Author: Glenn Jocher <glenn.jocher@ultralytics.com>
Date:   Tue Nov 22 21:27:33 2022 +0100

branch  master.

**Comment by glenn-jocher** [comment] 2022-12-06 06:26
@leemengwei 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. ONNX --half export and inference works correctly in our tests, we are unable to reproduce any issue:
<img width="1257" alt="Screenshot 2022-12-05 at 22 25 29" src="https://user-images.githubusercontent.com/26833433/205837312-7a90d6ad-0ffb-4419-aba0-68ca3202ea7f.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Closed as completed** 2022-12-19 11:10 UTC
Labels: question
