### ISSUE TITLE
tfjs YOLOv5n export fail

### ISSUE THREAD

**Issue by rtm-1dyakonov** [ultralytics/yolov5#6360] opened 2022-01-20 07:44 UTC
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

I've used the export.py script from the latest release 6.0 to convert yolov5n.pt to TensorFlow.js format. However, this error appears all the time: 

![изображение](https://user-images.githubusercontent.com/65365762/150294922-afada1e9-7e93-4fa8-963c-34dabaa3eb1a.png)

Do you know how to solve it? 
I've tried to do the same exact exporting with YOLOv5s and YOLOv5m, and it went fine. The only issue is with the YOLOv5n version...

### Environment

I am training in Google Colab with GPU

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by rtm-1dyakonov** [comment] 2022-01-20 07:51
I've also tried not mine but published with the latest release pre-trained weights yolo5n.pt and yolo5n6.pt. There is the same problem 
![изображение](https://user-images.githubusercontent.com/65365762/150295962-3261b437-1c8d-4284-b1e3-13a3c7697e1e.png)

**Comment by Hyrtsi** [comment] 2022-01-20 13:42
@rtm-1dyakonov The error message `no CUDA-capable device is detected` is one thing, then the `NotFoundError` is another thing.

The hardware you're trying to run the model on is missing NVIDIA drivers and a suitable CUDA. Could you check your installation? Be careful with the support matrix: your hardware must match exactly your drivers, CUDA, TensorFlow and Python versions. If you prefer using docker, note that the `Dockerfile` in this repo has the following line commented away that you might want to run 

`# RUN pip install --no-cache torch==1.10.0+cu113 torchvision==0.11.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html`

If you don't use docker please check the installation steps from the `Dockerfile` anyways since you're clearly either missing an dependency related to CUDA or you're having a version mismatch. Your host system NVIDIA drivers must be up to date as they are not forward compatible.

Could you rollback your Python from `3.7` to `3.6`? I'd suggest using `conda` or another python environment tool.

Then, your command is `yolov5n6_base.pt` where as the error says `yolov5n6_base.pb` so the file extension is different. Could that fix the issue?

I hope any of these ideas helped you.

**Comment by rtm-1dyakonov** [comment] 2022-01-20 14:18
@Hyrtsi where do you see the error message `no CUDA-capable device is detected`?

I don't use Docker. My code is in Colab. I can't understand why other versions like yolov5s or yolov5m export well but yolov5n doesn't.

**Comment by rtm-1dyakonov** [comment] 2022-01-20 14:26
@Hyrtsi And also about the extension issue: according to the export.py script from the latest release 6.0 I am able to use files with .pt extension only

![изображение](https://user-images.githubusercontent.com/65365762/150357140-9e378525-fd55-453e-8fb7-ca01c741a35e.png)

**Comment by glenn-jocher** [comment] 2022-01-20 23:02
@rtm-1dyakonov 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. Your error is not reproducible. YOLOv5n TF.js export works correctly in a Google Colab environment:
```python
!python export.py --weights yolov5n.pt --include tfjs
```

<img width="1289" alt="Screen Shot 2022-01-20 at 1 00 51 PM" src="https://user-images.githubusercontent.com/26833433/150435849-78f1a0f7-120a-4c66-8083-bd86089811f2.png">

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by rtm-1dyakonov** [comment] 2022-01-21 07:45
> Your error is not reproducible

@glenn-jocher yeah, I used the script from master and now it's working well. Thanx!

**Comment by glenn-jocher** [comment] 2022-01-21 19:53
@rtm-1dyakonov great!

**Closed as completed by glenn-jocher** 2022-01-21 19:53 UTC
