### ISSUE TITLE
torchhub load model python version restriction

### ISSUE THREAD

**Issue by LIU-FAYANG** [ultralytics/yolov5#3543] opened 2021-06-09 05:26 UTC
## ❔Question
Hi, it looks similar to the model loading opencv-python problem, could you help cancel the pytorchhub python version check? 
Also, can I ask what's the right way to load the model locally, thanks a lot!

## Additional context
Traceback (most recent call last):
  File "loitering_main.py", line 373, in <module>
    main()
  File "loitering_main.py", line 120, in main
    detector = torch.hub.load('ultralytics/yolov5', 'yolov5s',force_reload= True)
  File "/home/psl/.local/lib/python3.6/site-packages/torch/hub.py", line 370, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/psl/.local/lib/python3.6/site-packages/torch/hub.py", line 399, in _load_local
    model = entry(*args, **kwargs)
  File "/home/psl/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 70, in yolov5s
    return _create('yolov5s', pretrained, channels, classes, autoshape, verbose, device)
  File "/home/psl/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 34, in _create
    exclude=('tensorboard', 'pycocotools', 'thop', 'opencv-python'))
  File "/home/psl/.cache/torch/hub/ultralytics_yolov5_master/utils/general.py", line 151, in check_requirements
    check_python()  # check python version
  File "/home/psl/.cache/torch/hub/ultralytics_yolov5_master/utils/general.py", line 144, in check_python
    assert result, f'Python {minimum} required by YOLOv5, but Python {current} is currently installed'
AssertionError: Python 3.7.0 required by YOLOv5, but Python 3.6.9 is currently installed

**Comment by glenn-jocher** [comment] 2021-06-09 09:03
@LIU-FAYANG unfortunately 3.6.9 doesn't pass CI checks currently. It looks like the cause is inability to install pycocotools>2.0 with python 3.6.9. I'll think about how to work around this!
https://github.com/ultralytics/yolov5/pull/3375/checks?check_run_id=2782033417

**Comment by glenn-jocher** [comment] 2021-06-09 09:08
@LIU-FAYANG I think the best approach would be to comment pycocotools in requirements.txt and insert a special check_requirements call in test.py right before pycocotools is imported. I think 3.6.9 might pass CI after these updates. I will try to implement these changes today.

TODO: install pycocotools on-demand only.

**Comment by glenn-jocher** [comment] 2021-06-09 09:24
@LIU-FAYANG I've updated pycocotools handling in #3547, and merged updated master into https://github.com/ultralytics/yolov5/pull/3375, which is now running CI tests on all python versions. If the 3.6.9 tests pass, I will create a new PR to reduce the YOLOv5 python requirement to 3.6.9, and then this issue should be resolved.

**Comment by glenn-jocher** [comment] 2021-06-09 09:34
@LIU-FAYANG good news 😃! Your original issue may now be fixed ✅ in PRs #3547 and #3548. Python minimum version reduced to 3.6.2. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Closed as completed** 2021-06-09 09:34 UTC
Labels: question

**Comment by LIU-FAYANG** [comment] 2021-06-09 09:47
@glenn-jocher Hi, it works now, thanks for your kind help! :)

**Comment by glenn-jocher** [comment] 2021-06-09 09:56
@LIU-FAYANG great, glad to hear it! Let us know if you run into any other problems :)
