### ISSUE TITLE
Incorrect CUDA devices setting and accessing

### ISSUE THREAD

**Issue by seliu** [ultralytics/yolov5#8816] opened 2022-08-01 03:04 UTC
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Multi-GPU

### Bug

In utils/torch_utils.py line 76 (as copied below), the setting doesn't limit torch.cuda.device_count() to the specified devices:
```
    elif device:  # non-cpu device requested
        os.environ['CUDA_VISIBLE_DEVICES'] = device  # set environment variable - must be before assert is_available()
        # print( f'device_count: {torch.cuda.device_count()}' )
        # for i in range( torch.cuda.device_count() ):
        #     print( f'device_name {i}: {torch.cuda.get_device_name(i)}')
        #     print( f'device_prop {i}: {torch.cuda.get_device_properties(i)}')
```
The commented-out lines are used for debugging, which still returns all devices on the host machine instead of visible ones.

As a result, the code in line 91 (as copied below) would actually access the index from all devices instead of user-specified ones:
```
        for i, d in enumerate(devices):
            p = torch.cuda.get_device_properties(i)
            # p = torch.cuda.get_device_properties( int( d ) ) # sean 20220728
            s += f"{'' if i == 0 else space}CUDA:{d} ({p.name}, {p.total_memory / (1 << 20):.0f}MiB)\n"  # bytes to MB

```
The commented-out line is a temporary fix to replace the one before it for my locally usage of 4 out of 8 nv cards.

### Environment

CPU: Xeon E5-2620 x 2
GPU: Titan RTX x 4 + GTX 1080 Ti x 4
OS: Ubuntu 20.04
YOLOv5: latest

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment] 2022-08-01 04:34
@seliu Can you confirm that this actually uses all available GPUs and not only the specified ones? I've been using `--device` flag quite a bit these days and it only uses the specified devices. Maybe, the case here is that the info is printed out for all devices but only the devices specified are used?

**Comment by seliu** [comment] 2022-08-01 08:05
For better illustration, I did a simplified experiment on a machine with two cards: 0 - GTX-1080Ti 11G, 1 - GTX-1080 8G

Run a multi-GPU training with the command line similar to below one:
`python -m torch.distributed.run --nproc_per_node 1 train.py --device 1 ...`

Now go check the usage of GPUs by `nvidia-smi`, it shows that card 0 (1080Ti) is used instead of card 1 (1080):

![multi-gpu debug](https://user-images.githubusercontent.com/33053549/182100797-9d0d5fc6-f1ee-42fe-9097-c382b76af8f5.png)

To double confirm, modify the training command as below and run:
`python -m torch.distributed.run --nproc_per_node 1 train.py --device 0 ...`

Go check the usage of GPUs and still the card 0 is used:

![multi-gpu debug 2](https://user-images.githubusercontent.com/33053549/182101329-037d4038-b6dd-4a87-9c77-495adc4aa2e2.png)

Hopefully this helps clarify the issue.

**Comment by AyushExel** [comment] 2022-08-01 08:23
@seliu ok got it. So the issue is that it's using a different card than the specified one. I thought it was using all cards. 
Can you please specify the torch version you're using?

**Comment by seliu** [comment] 2022-08-01 08:28
It's `torch 1.12.0`

**Comment by glenn-jocher** [comment] 2022-08-01 09:14
@seliu DDP training is prohibited in torch 1.12 due to a known torch issue. This has been resolved in nightly.
https://github.com/ultralytics/yolov5/blob/7b9cc3205ae2cd9fdb0a56ca2818e17c5ae8346e/utils/torch_utils.py#L37-L46

As I recommended in my Multi-GPU tutorial always use Docker for DDP trainings which already ships with the correct torch version.

**Closed as completed** 2022-08-01 09:15 UTC
Labels: bug
