### ISSUE TITLE
TypeError: 'float' object is not iterable using YOLOv5 v4.0

### ISSUE THREAD

**Issue by noeltong** [ultralytics/yolov5#2828] opened 2021-04-18 03:17 UTC
I tried to train on yolov5 v5.0 using the command following the README.md, it worked well.

```
python ./train.py --data ../volleyball.yaml --cfg ./models/yolov5s.yaml --weights ./yolov5s.pt --batch-size 40
```

But when I used the same command to train on YOLOv5 v4.0, it comes out that an error occured which said "TypeError: 'float' object is not iterable", and the train is stopped.

How can i do to train on yolov5 v4.0?

```
Scanning '/home/student/Documents/YOLOv5-test/volleyball/labels.cache' for images and labels... 1226 found, 57 missing, 0 empty, 0 corrupted: 100%|██████████████| 1283/1283 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "./train.py", line 519, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "./train.py", line 189, in train
    dataloader, dataset = create_dataloader(train_path, imgsz, batch_size, gs, opt,
  File "/home/student/Documents/YOLOv5-test/yolov5/utils/datasets.py", line 62, in create_dataloader
    dataset = LoadImagesAndLabels(path, imgsz, batch_size,
  File "/home/student/Documents/YOLOv5-test/yolov5/utils/datasets.py", line 385, in __init__
    labels, shapes = zip(*cache.values())
TypeError: 'float' object is not iterable
```

**Comment by glenn-jocher** [comment] 2021-04-18 09:43
@noeltong I used your example code in a notebook with v4.0 and everything works correctly, so your issue is not reproducible. 

If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!

<img width="1381" alt="Screenshot 2021-04-18 at 11 42 40" src="https://user-images.githubusercontent.com/26833433/115141190-4bca5d00-a03b-11eb-9f21-df14d724b938.png">

**Comment by ziyu-n** [comment] 2021-04-20 09:49
I ran into the same problem.
but it is not reproducible.
My other computer did not have this problem .
sad

**Comment by CoderTylor** [comment] 2021-04-22 17:27
I ran the same problem find the solution
that's because you have already trained your images in other yolov5 version and made a cache file, delete all the cache file and rerun it, it works

**Closed as completed** 2021-05-21 02:30 UTC
Labels: question

**Comment by 865315255** [comment] 2021-06-23 10:20
I have encountered the same problem, you need to delete the cache file under the labels folder
![0](https://user-images.githubusercontent.com/67730998/123080636-b939a600-d44f-11eb-9a67-4e58dd5e0d2e.PNG)
