### ISSUE TITLE
The detect result of pytorch model is different from onnx model. It seems different deep learning framework has different output

### ISSUE THREAD

**Issue by zoubaihan** [ultralytics/yolov5#6587] opened 2022-02-09 07:45 UTC
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection, Export

### Bug

Hello, here is a question that confuse me a lot. I download the model **yolov5m.onnx** and **yolov5m.pt** , and the test command is as follow:

onnx model tested on COCO:
`python detect.py --source /datasets/coco128/images/train2017 --weights /data/zoubaihan/pyproject/yolov5/yolov5m.onnx`

One of the image detected by **onnx** model is as follow:
![000000000263](https://user-images.githubusercontent.com/60840371/153144366-03888b10-df40-4cde-964e-345b3ea9ffd7.jpg)

pytorch model tested on COCO:
`python detect.py --source /datasets/coco128/images/train2017 --weights /data/zoubaihan/pyproject/yolov5/yolov5m.pt`

While the same input image detected by **pytorch** model is as follow:
![000000000263](https://user-images.githubusercontent.com/60840371/153144403-ce35a7e4-71cd-4df5-b203-a3e523624b77.jpg)

Jesus! **Why the same model and the same weight under different deeplearning framework output different results?**

I have also tried to convert some other deep learning models between different deep learning frameworks, but the output results are often different, or even very different. Could you please explain why this is?

I also tried to use export.py to **convert model from pytorch to onnx**, but their results is also not equal. The command is as follow:
`python export.py --weights yolov5m.pt --include onnx `

But another confusing problem came out: the file size of the output onnx model is not equal to the onnx model I download from your github. Is the **yolov5m.onnx** model you put in the release really converted by you by running **export.py**?

### Minimal Reproducible Example

onnx model tested on COCO:
`python detect.py --source /datasets/coco128/images/train2017 --weights /data/zoubaihan/pyproject/yolov5/yolov5m.onnx`

pytorch model tested on COCO:
`python detect.py --source /datasets/coco128/images/train2017 --weights /data/zoubaihan/pyproject/yolov5/yolov5m.pt`

I also tried to use export.py to **convert model from pytorch to onnx**, but their results is also not equal. The command is as follow:
`python export.py --weights yolov5m.pt --include onnx `

### Additional

I tried the export.py and other convert tools, but all not work well. Their output results are not the same.
Anybody know why?
Here is the collection of model converter:
[https://github.com/ysh329/deep-learning-model-convertor](https://github.com/ysh329/deep-learning-model-convertor)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment] 2022-02-09 10:11
@zoubaihan closing as duplicate of #6586

**Closed as completed by glenn-jocher** 2022-02-09 10:11 UTC
Labels: bug, duplicate
