### ISSUE TITLE
rtsp source

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#1403] opened 2020-11-16 03:36 UTC
## ❔Question

Fusing layers... 
Model Summary: 232 layers, 7459581 parameters, 0 gradients
1/1: rtsp://root:root@10.10.237.2/cam0_2...  success (320x240 at 0.00 FPS).

0: 480x640 3 persons, 1 tvs, Done. (7.801s)
Traceback (most recent call last):
  File "detect.py", line 172, in <module>
    detect()
  File "detect.py", line 118, in detect
    cv2.imshow(p, im0)
**SystemError: <built-in function imshow> returned NULL without setting an error**
terminate called without an active exception

Can you tell me how to resolve this problem?

**Comment by glenn-jocher** [comment] 2020-11-16 08:47
@leeyunhome I'd recommend you raise this issue on the opencv repo as the error generates there.
https://github.com/opencv/opencv

**Comment by leeyunhome** [comment] 2020-11-16 19:02
> @leeyunhome I'd recommend you raise this issue on the opencv repo as the error generates there.
> https://github.com/opencv/opencv

Hello, @glenn-jocher 

I asked the following questions:
https://github.com/opencv/opencv/issues/18821

Thank you.

**Comment by glenn-jocher** [comment] 2020-11-16 19:32
@leeyunhome great! I think this section of code was working in previous cv2 versions,  the cv2.imshow() command is one of the most basic, it simply displays an image.

**Comment by LU4E** [comment] 2020-11-17 09:46
I have the same problem.
The code is not working after I update my mac(now is macOS Big Sur). It work well before I update the system.
The same question occur when I run the detect with webcam.

`python detect.py --source 0 --weights yolov5s.pt --conf 0.4                                                       311  17:46:15    3.66    2.38G 
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='', exist_ok=False, img_size=640, iou_thres=0.45, name='exp', project='runs/detect', save_conf=False, save_txt=False, source='0', update=False, view_img=False, weights=['yolov5s.pt'])
Using torch 1.6.0 CPU

Fusing layers...
Model Summary: 232 layers, 7459581 parameters, 0 gradients
1/1: 0...  success (1280x720 at 12.00 FPS).

0: 384x640 Done. (0.304s)
Traceback (most recent call last):
  File "detect.py", line 172, in <module>
    detect()
  File "detect.py", line 118, in detect
    cv2.imshow(p, im0)
SystemError: <built-in function imshow> returned NULL without setting an error`

**Comment by glenn-jocher** [comment] 2020-11-17 11:29
@LU4E ah, yes perhaps this is the cause. I updated my MacOS 11.0.1 Big Sur the other day and now I also can't use the cv2.imshow() function.

**Comment by Kaiwen6** [comment] 2020-11-18 01:51
cv2.imshow('p', im0)
Add the ' 'above the p

**Comment by leeyunhome** [comment] 2020-11-18 08:32
> I have the same problem.
> The code is not working after I update my mac(now is macOS Big Sur). It work well before I update the system.
> The same question occur when I run the detect with webcam.
> 
> `python detect.py --source 0 --weights yolov5s.pt --conf 0.4    311  17:46:15   3.66   2.38G 
> Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='', exist_ok=False, img_size=640, iou_thres=0.45, name='exp', project='runs/detect', save_conf=False, save_txt=False, source='0', update=False, view_img=False, weights=['yolov5s.pt'])
> Using torch 1.6.0 CPU
> 
> Fusing layers...
> Model Summary: 232 layers, 7459581 parameters, 0 gradients
> 1/1: 0... success (1280x720 at 12.00 FPS).
> 
> 0: 384x640 Done. (0.304s)
> Traceback (most recent call last):
> File "detect.py", line 172, in
> detect()
> File "detect.py", line 118, in detect
> cv2.imshow(p, im0)
> SystemError: returned NULL without setting an error`

Thank you.

**Comment by leeyunhome** [comment] 2020-11-18 08:33
> cv2.imshow('p', im0)
> Add the ' 'above the p

Thank you. 👍

**Comment by leeyunhome** [comment] 2020-11-18 08:34
> cv2.imshow('p', im0)
> Add the ' 'above the p

Hello,

I solved it thanks to you.

Can I ask why you are doing this?

Thank you.

**Comment by glenn-jocher** [comment] 2020-11-18 09:02
@Kaiwen6 ah thanks for spotting this!

**Comment by glenn-jocher** [comment] 2020-11-18 09:04
This issue should now be resolved by the following PR. The problem was p was a posixpath rather than a str.

- PosixPath to str webcam bug fix #1437

**Closed as completed** 2020-11-18 09:03 UTC
Labels: question
